'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),M=require('../app/src/main/assets/model.js');
const meal={id:'meal',date:'2026-10-08',name:'米饭',grams:150,lowKcal:160,highKcal:220,kcal:190,note:'历史估算'};
const favorite=(patch={})=>({id:'favorite',name:'米饭',grams:150,lowKcal:160,highKcal:220,note:'参考值',...patch});
function storage(raw){const map=new Map(raw?[[M.KEY,raw]]:[]);return {map,getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,v)};}
test('schema 3 migration keeps ledger, nutrition, weight, settings and untouched original backup',()=>{const old=M.addWeight(M.addNutrition(M.defaultState(),meal),{id:'weight',date:'2026-10-08',kg:63.25});old.expenses.push({id:'expense',date:'2026-10-08',type:'expense',category:'meals',amount:1234,source:'保留',note:'原文'});old.version=3;delete old.favorites;const raw=JSON.stringify(old,null,2),store=storage(raw),next=M.load(store);assert.equal(next.version,5);for(const key of ['expenses','nutrition','weights','settings'])assert.deepEqual(next[key],old[key]);assert.deepEqual(next.favorites,[]);assert.equal(store.getItem(M.KEY),raw);M.save(store,M.addFavorite(next,favorite()));assert.equal(store.getItem(M.KEY+'-before-v4'),raw);assert.equal(M.load(store).favorites.length,1);M.save(store,M.load(store));assert.equal(store.getItem(M.KEY+'-before-v4'),raw);});
test('schema 1 and 2 retain both migration backup keys, schema 4 round trips independently',()=>{for(const version of [1,2]){const old={...M.defaultState(),version},raw=JSON.stringify(old),store=storage(raw);M.save(store,M.load(store));assert.equal(store.getItem(M.KEY+'-before-v3'),raw);assert.equal(store.getItem(M.KEY+'-before-v4'),raw);}const state=M.addFavorite(M.defaultState(),favorite());assert.deepEqual(M.parse(JSON.stringify(state)),state);const parsed=M.parse(JSON.stringify(state));parsed.favorites[0].grams=200;assert.equal(state.favorites[0].grams,150);});
test('failed v4 safety-copy or main write leaves raw old data untouched',()=>{for(const failKey of [M.KEY+'-before-v4',M.KEY]){const raw=JSON.stringify({...M.defaultState(),version:3}),store=storage(raw),write=store.setItem;store.setItem=(k,v)=>{if(k===failKey)throw Error('full');write(k,v);};assert.throws(()=>M.save(store,M.load(store)));assert.equal(store.getItem(M.KEY),raw);}});
test('favorites create/edit/delete are immutable and cannot rewrite history',()=>{const state=M.addNutrition(M.defaultState(),meal),original=JSON.stringify(state),copy=M.favoriteFromNutrition(meal,'favorite'),a=M.addFavorite(state,copy),b=M.updateFavorite(a,'favorite',favorite({grams:300,lowKcal:400,highKcal:500})),c=M.removeFavorite(b,'favorite');assert.equal(JSON.stringify(state),original);assert.deepEqual(c.nutrition,state.nutrition);assert.equal(a.favorites[0].grams,150);assert.equal(b.favorites[0].grams,300);assert.equal(c.favorites.length,0);assert.throws(()=>M.updateFavorite(a,'missing',favorite()));assert.throws(()=>M.removeFavorite(a,'missing'));});
test('duplicate name normalization handles case, whitespace and Unicode width',()=>{const state=M.addFavorite(M.defaultState(),favorite({name:' Milk 饭 '}));assert.equal(M.findFavorite(state,'ＭＩＬＫ　饭').id,'favorite');assert.throws(()=>M.addFavorite(state,favorite({id:'second',name:'milk饭'})));assert.equal(M.findFavorite(state,'milk饭','favorite'),null);assert.throws(()=>M.validate({...state,favorites:[favorite(),favorite({id:'second',name:' 米 饭 '})]}));});
test('favorite validation rejects missing/zero/negative/nonfinite grams and malformed energy but accepts zero calories',()=>{for(const grams of ['',0,-1,NaN,Infinity,null,undefined,'150'])assert.throws(()=>M.addFavorite(M.defaultState(),favorite({grams})));for(const patch of [{name:''},{name:'  '},{lowKcal:''},{lowKcal:-1},{lowKcal:NaN},{highKcal:Infinity},{highKcal:100}])assert.throws(()=>M.addFavorite(M.defaultState(),favorite(patch)));assert.equal(M.addFavorite(M.defaultState(),favorite({lowKcal:0,highKcal:0})).favorites[0].highKcal,0);});
test('portion scaling always reads unchanged baseline and rejects invalid or excessive results',()=>{const base=favorite({grams:120,lowKcal:180,highKcal:240}),snapshot=JSON.stringify(base);for(const [grams,low,high]of [[60,90,120],[240,360,480],[120,180,240],[30,45,60]])assert.deepEqual(M.scaleFavorite(base,grams),{grams,lowKcal:low,highKcal:high});assert.equal(JSON.stringify(base),snapshot);for(const grams of [0,-2,NaN,Infinity,'60'])assert.throws(()=>M.scaleFavorite(base,grams));assert.throws(()=>M.scaleFavorite(favorite({grams:0.01}),1000000));assert.deepEqual(M.scaleFavorite(favorite({lowKcal:0,highKcal:0}),300),{grams:300,lowKcal:0,highKcal:0});});
