'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
function setup(saved){const base=path.resolve(__dirname,'../app/src/main/assets'),dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'https://app.local/',runScripts:'outside-only'}),w=dom.window,calls=[];w.scrollTo=()=>{};w.alert=text=>calls.push(['alert',text]);w.confirm=()=>true;w.setInterval=()=>0;w.Android={notify:()=>{},captureFoodPhoto:(...args)=>calls.push(['camera',...args]),chooseFoodPhoto:(...args)=>calls.push(['gallery',...args]),checkForUpdates:(...args)=>calls.push(['updates',...args]),exportBackup:text=>calls.push(['export',text])};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.eval(fs.readFileSync(path.join(base,'model.js'),'utf8'));if(saved!==undefined)w.localStorage.setItem(w.BudgetModel.KEY,typeof saved==='string'?saved:JSON.stringify(saved));w.eval(fs.readFileSync(path.join(base,'app.js'),'utf8'));const $=id=>w.document.getElementById(id);return {w,calls,$,fill:(id,v)=>{$(id).value=v;},submit:id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})),state:()=>JSON.parse(w.localStorage.getItem(w.BudgetModel.KEY)),close:()=>w.close()};}
const M=require('../app/src/main/assets/model.js');
const meal={id:'meal',date:'2026-10-08',name:'午餐米饭',grams:120,lowKcal:180,highKcal:240,kcal:210,note:'原始照片估算'};
const fav={id:'fav',name:'常用米饭',grams:120,lowKcal:180,highKcal:240,note:'参考'};
const initial=()=>M.addFavorite(M.addNutrition(M.defaultState(),meal),fav);
function input(e,id,value){e.fill(id,value);e.$(id).dispatchEvent(new e.w.Event('input',{bubbles:true}));}
function use(e){e.w.document.querySelector('[data-favorite-use]').click();}
function edit(e){e.w.document.querySelector('[data-favorite-edit]').click();}
function fillFavorite(e,name='新米饭'){for(const [id,v]of Object.entries({'favorite-name':name,'favorite-grams':'100','favorite-low':'100','favorite-high':'150','favorite-note':'独立副本'}))e.fill(id,v);}
test('favorite prefill has no write; repeated gram changes scale original snapshot, explicit submit logs once',()=>{const e=setup(initial());try{const before=JSON.stringify(e.state());use(e);assert.equal(e.$('food-name').value,fav.name);assert.equal(e.$('food-grams').value,'120');assert.equal(e.$('favorite-select').value,'fav');for(const [g,l,h]of [[60,90,120],[240,360,480],[120,180,240]]){input(e,'food-grams',g);assert.equal(Number(e.$('food-low').value),l);assert.equal(Number(e.$('food-high').value),h);}assert.equal(JSON.stringify(e.state()),before);e.submit('food-form');assert.equal(e.state().nutrition.length,2);assert.equal(e.state().favorites[0].grams,120);assert.deepEqual(e.state().nutrition.find(r=>r.id==='meal'),meal);}finally{e.close();}});
test('manual energy input stops scaling, resume is explicit, calculator also stops auto scaling',()=>{const e=setup(initial());try{use(e);input(e,'food-low','10');input(e,'food-high','20');input(e,'food-grams','240');assert.equal(e.$('food-low').value,'10');assert.equal(e.$('food-high').value,'20');assert.match(e.$('favorite-scale-status').textContent,/停止自动/);assert.equal(e.$('resume-favorite-scale').hidden,false);e.$('resume-favorite-scale').click();assert.equal(e.$('food-low').value,'360');e.fill('label-energy','418.4');e.$('calculate-label').click();assert.equal(e.$('food-low').value,'240');input(e,'food-grams','120');assert.equal(e.$('food-low').value,'240');e.submit('food-form');assert.equal(e.state().nutrition.at(-1).lowKcal,240);}finally{e.close();}});
test('cancel food prefill and new favorite dialog writes nothing; normal manual/photo modes never inherit scaling',()=>{const e=setup(initial());try{const before=JSON.stringify(e.state());use(e);input(e,'food-grams','240');e.$('close-food').click();assert.equal(JSON.stringify(e.state()),before);e.$('add-favorite').click();fillFavorite(e);assert.equal(e.w.handleBack(),true);assert.equal(e.$('favorite-dialog').open,false);assert.equal(JSON.stringify(e.state()),before);e.$('add-food').click();assert.equal(e.$('favorite-scale-status').hidden,true);input(e,'food-low','22');input(e,'food-grams','123');assert.equal(e.$('food-low').value,'22');e.$('close-food').click();e.w.receiveFoodRecognition(JSON.stringify({name:'照片',portionGrams:100,caloriesLow:40,caloriesHigh:80}));input(e,'food-grams','200');assert.equal(e.$('food-low').value,'40');}finally{e.close();}});
test('save favorite from existing logged food copies persisted fields despite unsaved food edits',()=>{const e=setup(initial());try{e.fill('food-day',meal.date);e.$('food-day').dispatchEvent(new e.w.Event('change'));e.$('food-list').querySelector('button').click();input(e,'food-name','未保存修改');input(e,'food-grams','999');e.$('favorite-from-food').click();assert.equal(e.$('favorite-name').value,meal.name);assert.equal(e.$('favorite-grams').value,'120');assert.equal(e.state().favorites.length,1);e.fill('favorite-name','午餐副本');e.submit('favorite-form');assert.equal(e.state().favorites.length,2);assert.equal(e.state().nutrition.length,1);assert.deepEqual(e.state().nutrition[0],meal);assert.equal(e.$('food-dialog').open,true);e.$('close-food').click();}finally{e.close();}});
test('normalized duplicate asks replace or cancel to rename without silent duplication',()=>{const base=M.addFavorite(M.defaultState(),{...fav,name:'Milk 饭'}),e=setup(base),questions=[];try{e.$('add-favorite').click();fillFavorite(e,'ＭＩＬＫ　饭');e.w.confirm=text=>{questions.push(text);return false;};e.submit('favorite-form');assert.equal(e.state().favorites.length,1);assert.equal(e.state().favorites[0].grams,120);assert.equal(e.$('favorite-dialog').open,true);assert.match(questions[0],/替换/);e.fill('favorite-name','新名字');e.submit('favorite-form');assert.equal(e.state().favorites.length,2);e.$('add-favorite').click();fillFavorite(e,'milk饭');e.w.confirm=()=>true;e.submit('favorite-form');assert.equal(e.state().favorites.length,2);assert.equal(e.state().favorites.find(r=>r.id==='fav').grams,100);}finally{e.close();}});
test('favorite edit and deletion confirmation preserve every historical meal and previous copied favorite',()=>{const base=M.addFavorite(initial(),{...fav,id:'copy',name:'此前副本'}),e=setup(base);try{edit(e);e.fill('favorite-grams','300');e.$('close-favorite').click();assert.deepEqual(e.state(),base);edit(e);e.fill('favorite-grams','300');e.fill('favorite-low','200');e.submit('favorite-form');assert.equal(e.state().favorites[0].grams,300);assert.deepEqual(e.state().favorites[1],base.favorites[1]);assert.deepEqual(e.state().nutrition,base.nutrition);edit(e);e.w.confirm=()=>false;e.$('delete-favorite').click();assert.equal(e.state().favorites.length,2);assert.equal(e.$('favorite-dialog').open,true);e.w.confirm=()=>true;e.$('delete-favorite').click();assert.equal(e.state().favorites.length,1);assert.deepEqual(e.state().nutrition,base.nutrition);}finally{e.close();}});
test('editing favorite into another name offers explicit replacement of both entries',()=>{const base=M.addFavorite(initial(),{...fav,id:'other',name:'第二个'}),e=setup(base);try{edit(e);e.fill('favorite-name','第二个');e.w.confirm=()=>false;e.submit('favorite-form');assert.deepEqual(e.state(),base);e.w.confirm=()=>true;e.submit('favorite-form');assert.equal(e.state().favorites.length,1);assert.equal(e.state().favorites[0].id,'other');assert.deepEqual(e.state().nutrition,base.nutrition);}finally{e.close();}});
test('invalid favorite values never save, zero-calorie favorite is valid, invalid scaled grams cannot log',()=>{const e=setup();try{e.$('add-favorite').click();fillFavorite(e);for(const v of ['',0,-1,'NaN','Infinity','1e3']){e.fill('favorite-grams',v);e.submit('favorite-form');assert.equal(e.state(),null);}e.fill('favorite-grams','100');for(const [low,high]of [['','50'],['-1','50'],['20','10'],['NaN','50']]){e.fill('favorite-low',low);e.fill('favorite-high',high);e.submit('favorite-form');assert.equal(e.state(),null);}e.fill('favorite-low','0');e.fill('favorite-high','0');e.submit('favorite-form');assert.equal(e.state().favorites[0].lowKcal,0);use(e);for(const v of ['',0,-1,'NaN']){input(e,'food-grams',v);e.submit('food-form');assert.equal(e.state().nutrition.length,0);}input(e,'food-grams','200');assert.equal(e.$('food-high').value,'0');e.submit('food-form');assert.equal(e.state().nutrition[0].kcal,0);}finally{e.close();}});
test('select favorite inside new meal prefills and historical edit hides selector',()=>{const e=setup(initial());try{e.$('add-food').click();e.fill('favorite-select','fav');e.$('favorite-select').dispatchEvent(new e.w.Event('change'));assert.equal(e.$('food-name').value,fav.name);assert.equal(e.state().nutrition.length,1);e.$('close-food').click();e.fill('food-day',meal.date);e.$('food-day').dispatchEvent(new e.w.Event('change'));e.$('food-list').querySelector('button').click();assert.equal(e.$('favorite-select-label').hidden,true);assert.equal(e.$('favorite-scale-status').hidden,true);input(e,'food-grams','240');assert.equal(e.$('food-low').value,'180');}finally{e.close();}});
test('schema 3 migration on favorite save, reload, export, import and cancellation preserve all data',()=>{const old=initial();old.version=3;delete old.favorites;const raw=JSON.stringify(old,null,2),e=setup(raw);let saved;try{e.$('add-favorite').click();fillFavorite(e);e.submit('favorite-form');saved=e.state();assert.equal(saved.version,5);assert.equal(e.w.localStorage.getItem(M.KEY+'-before-v4'),raw);assert.deepEqual(saved.nutrition,old.nutrition);e.$('export').click();assert.deepEqual(JSON.parse(e.calls.at(-1)[1]),saved);e.w.confirm=()=>false;e.w.receiveBackup(raw);assert.deepEqual(e.state(),saved);}finally{e.close();}const reload=setup(saved);try{assert.equal(reload.w.document.querySelectorAll('[data-favorite-use]').length,1);reload.w.receiveBackup(JSON.stringify(saved));assert.deepEqual(reload.state(),saved);reload.w.receiveBackup(raw);assert.equal(reload.state().favorites.length,0);assert.deepEqual(reload.state().nutrition,old.nutrition);const before=reload.w.localStorage.getItem(M.KEY);reload.w.receiveBackup(JSON.stringify({...saved,favorites:[{...fav,grams:0}]}));assert.equal(reload.w.localStorage.getItem(M.KEY),before);}finally{reload.close();}});
test('duplicate food submit after close logs once, next intentional open can log another',()=>{const e=setup(initial());try{use(e);e.submit('food-form');assert.equal(e.state().nutrition.length,2);e.submit('food-form');e.submit('food-form');assert.equal(e.state().nutrition.length,2);use(e);e.submit('food-form');assert.equal(e.state().nutrition.length,3);e.submit('food-form');assert.equal(e.state().nutrition.length,3);}finally{e.close();}});
test('closed favorite form ignores duplicate submit; nested Back cancels favorite without changing meal draft',()=>{const e=setup(initial()),questions=[];try{e.$('add-favorite').click();fillFavorite(e);e.submit('favorite-form');assert.equal(e.state().favorites.length,2);e.w.confirm=text=>{questions.push(text);return true;};e.submit('favorite-form');assert.equal(e.state().favorites.length,2);assert.equal(questions.length,0);e.fill('food-day',meal.date);e.$('food-day').dispatchEvent(new e.w.Event('change'));e.$('food-list').querySelector('button').click();input(e,'food-name','未保存草稿');input(e,'food-grams','333');e.$('favorite-from-food').click();e.fill('favorite-name','不保存');assert.equal(e.w.handleBack(),true);assert.equal(e.$('favorite-dialog').open,false);assert.equal(e.$('food-dialog').open,true);assert.equal(e.$('food-name').value,'未保存草稿');assert.equal(e.$('food-grams').value,'333');assert.equal(e.state().favorites.length,2);assert.deepEqual(e.state().nutrition,[meal]);assert.equal(e.w.handleBack(),true);assert.equal(e.$('food-dialog').open,false);}finally{e.close();}});
