'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
function setup(saved){const base=path.resolve(__dirname,'../app/src/main/assets'),dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'https://app.local/',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};w.alert=()=>{};w.confirm=()=>true;w.setInterval=()=>0;w.Android={notify:()=>{}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.eval(fs.readFileSync(path.join(base,'model.js'),'utf8'));if(saved!==undefined)w.localStorage.setItem(w.BudgetModel.KEY,JSON.stringify(saved));w.eval(fs.readFileSync(path.join(base,'app.js'),'utf8'));return {w,dom,$:s=>w.document.querySelector(s),close:()=>w.close()};}
const row=date=>({date,type:'expense',category:'meals',amount:'20.83',note:'合成回归交易',source:'合成测试截图'});
function input(env,n,field,value){const e=env.$('#review-list').children[n].querySelector('[data-field='+field+']');if(field==='selected')e.checked=value;else e.value=value;e.dispatchEvent(new env.w.Event('input',{bubbles:true}));return e;}
function state(e){return JSON.parse(e.w.localStorage.getItem(e.w.BudgetModel.KEY));}
test('actual app bridge normalizes full dates and persists canonical values',()=>{const e=setup();try{for(const date of [' 2026-10-08 ','2026/10/8','2026年10月8日','2026-10-08T23:30:00-07:00']){e.w.receiveRecognition(JSON.stringify({records:[row(date)]}));assert.equal(e.$('[data-field=date]').value,'2026-10-08');assert.equal(e.$('.review-error').textContent,'');assert.ok(e.$('#review-list').textContent.includes(date.trim()));}e.$('#commit-review').click();assert.equal(state(e).expenses[0].date,'2026-10-08');assert.equal(state(e).expenses[0].amount,2083);}finally{e.close();}});
test('missing year defaults to 2026 automatically with no year confirmation',()=>{const e=setup();try{e.w.receiveRecognition(JSON.stringify({records:[{...row('10-08'),rawDate:'10-08'}]}));assert.equal(e.$('#review-year').value,'2026');assert.equal(e.$('[data-field=date]').value,'2026-10-08');assert.equal(e.$('[data-field=selected]').checked,true);assert.equal(e.$('.review-error').textContent,'');e.$('#commit-review').click();assert.equal(state(e).expenses[0].date,'2026-10-08');assert.equal(state(e).settings.statementYear,2026);}finally{e.close();}});
test('editing invalid date clears live warning and saves chosen cross-year dates',()=>{const e=setup();try{e.w.receiveRecognition(JSON.stringify({records:[row('2026-02-30'),{...row('01-02'),amount:'30'}]}));assert.match(e.$('.review-error').textContent,/日期/);input(e,0,'date','2025/12/31');assert.equal(e.$('.review-error').textContent,'');input(e,0,'selected',true);input(e,1,'date','2026年1月2日');input(e,1,'selected',true);e.$('#commit-review').click();assert.deepEqual(state(e).expenses.map(r=>r.date),['2025-12-31','2026-01-02']);}finally{e.close();}});
test('cancel and invalid selected rows do not persist or partially save',()=>{const e=setup();try{e.w.receiveRecognition(JSON.stringify({records:[row('2026-10-08')]}));e.w.confirm=()=>false;e.$('#commit-review').click();assert.equal(state(e),null);e.w.confirm=()=>true;e.w.receiveRecognition(JSON.stringify({records:[row('2026-10-08'),{...row('2026-02-30'),amount:'99'}]}));input(e,1,'selected',true);e.$('#commit-review').click();assert.equal(state(e),null);assert.match(e.$('#toast').textContent,/日期/);e.$('#close-review').click();assert.equal(e.$('#review-dialog').open,false);}finally{e.close();}});
test('initial blank AI date uses rawDate once, deliberate clearing never restores it',()=>{const e=setup();try{e.w.receiveRecognition(JSON.stringify({records:[{...row(''),rawDate:'10-08'}]}));assert.equal(e.$('[data-field=date]').value,'2026-10-08');e.$('#review-year').value='2024';e.$('#apply-review-year').click();assert.equal(e.$('[data-field=date]').value,'2024-10-08');input(e,0,'date','');assert.match(e.$('.review-error').textContent,/日期/);e.$('#apply-review-year').click();assert.equal(e.$('[data-field=date]').value,'');e.$('#commit-review').click();assert.equal(state(e).expenses.length,0);assert.equal(state(e).settings.statementYear,2024);}finally{e.close();}});

function year(e,value){e.$('#review-year').value=String(value);e.$('#review-year').dispatchEvent(new e.w.Event('change',{bubbles:true}));}
function dates(e){return [...e.w.document.querySelectorAll('[data-field=date]')].map(x=>x.value);}
test('local year auto saves, reapplies only inferred dates, reloads and reimports as 2025',()=>{
 let saved;const e=setup();try{
 e.w.receiveRecognition(JSON.stringify({records:[row('10-08'),{...row('2024/10/08'),amount:'22'},{...row('12-31'),amount:'23'}]}));
 input(e,2,'date','2023/12/31');year(e,2025);assert.equal(state(e).settings.statementYear,2025);assert.equal(state(e).expenses.length,0);assert.deepEqual(dates(e),['2025-10-08','2024-10-08','2023-12-31']);
 year(e,2027);assert.deepEqual(dates(e),['2027-10-08','2024-10-08','2023-12-31']);year(e,2025);e.$('#commit-review').click();saved=state(e);assert.deepEqual(saved.expenses.map(r=>r.date),['2025-10-08','2024-10-08','2023-12-31']);
 }finally{e.close();}
 const reloaded=setup(saved);try{assert.equal(reloaded.$('#review-year').value,'2025');reloaded.w.receiveRecognition(JSON.stringify({records:[row('11月2日')]}));assert.deepEqual(dates(reloaded),['2025-11-02']);reloaded.$('#commit-review').click();assert.equal(state(reloaded).expenses.at(-1).date,'2025-11-02');}finally{reloaded.close();}
});
test('changing year invalidates inferred leap days but preserves explicit leap dates and blocks atomic import',()=>{const e=setup();try{
 e.w.receiveRecognition(JSON.stringify({records:[row('02-29'),{...row('2024-02-29'),amount:'22'},{...row('04-31'),amount:'23'},{...row(''),amount:'24'}]}));
 assert.match(e.$('.review-error').textContent,/不存在/);year(e,2024);assert.equal(dates(e)[0],'2024-02-29');assert.equal(e.$('.review-error').textContent,'');year(e,2025);assert.equal(dates(e)[1],'2024-02-29');assert.match(e.$('.review-error').textContent,/不存在/);e.$('#commit-review').click();assert.equal(state(e).expenses.length,0);year(e,2024);assert.equal(dates(e)[0],'2024-02-29');assert.equal(e.$('.review-error').textContent,'');assert.match(e.$('#review-list').children[2].querySelector('.review-error').textContent,/不存在/);assert.match(e.$('#review-list').children[3].querySelector('.review-error').textContent,/日期为空/);
 }finally{e.close();}});
test('deliberate editing of the same full date pins it and clearing stays empty across year changes',()=>{const e=setup();try{
 e.w.receiveRecognition(JSON.stringify({records:[row('10-08'),{...row('11-09'),amount:'22'}]}));input(e,0,'date','2026-10-08');input(e,1,'date','');year(e,2025);assert.deepEqual(dates(e),['2026-10-08','']);assert.match(e.$('#review-list').children[1].querySelector('.review-error').textContent,/日期为空/);e.$('#commit-review').click();assert.equal(state(e).expenses.length,0);
 }finally{e.close();}});
