'use strict';const test=require('node:test'),assert=require('node:assert/strict'),M=require('../app/src/main/assets/model.js');const e=(id,amount,date='2026-10-08',category='meals')=>({id,amount,date,category,note:''});
test('defaults total 8600, only meals daily enabled, rent is never spent automatically',()=>{const s=M.defaultState();assert.equal(Object.values(s.settings.monthly).reduce((a,b)=>a+b),860000);assert.equal(s.settings.daily.meals,5000);assert.equal(Object.values(s.settings.daily).filter(x=>x!==null).length,1);assert.equal(M.total(s,'2026-10'),0);});
test('80% inclusive, 100% not over, greater than 100% over',()=>{assert.equal(M.level(3999,5000),'ok');assert.equal(M.level(4000,5000),'near');assert.equal(M.level(5000,5000),'near');assert.equal(M.level(5001,5000),'over');assert.equal(M.level(10000,null),'off');assert.equal(M.level(0,0),'ok');assert.equal(M.level(1,0),'over');});
test('CRUD and monthly/category/day totals are immutable',()=>{const s=M.defaultState(),a=M.add(s,e('a',2000)),b=M.add(a,e('b',3000,'2026-10-09')),c=M.add(b,e('c',10000,'2026-10-08','transport'));assert.equal(s.expenses.length,0);assert.equal(M.total(c,'2026-10'),15000);assert.equal(M.total(c,'2026-10','meals'),5000);assert.equal(M.total(c,'2026-10-08','meals'),2000);const d=M.update(c,'a',e('anything',4000));assert.equal(M.total(d,'2026-10'),17000);assert.equal(d.expenses[0].id,'a');assert.equal(M.total(M.remove(d,'a'),'2026-10'),13000);assert.throws(()=>M.update(d,'missing',e('x',1)));});
test('rollover follows calendar day/month with histories preserved',()=>{let s=M.defaultState();for(const x of [e('a',4000,'2026-10-31'),e('b',5000,'2026-11-01'),e('c',6000,'2027-01-01'),e('d',1000,'2026-12-31')])s=M.add(s,x);assert.equal(M.total(s,'2026-10'),4000);assert.equal(M.total(s,'2026-11'),5000);assert.equal(M.total(s,'2027-01'),6000);assert.equal(M.total(s,'2026-11-02'),0);assert.equal(s.expenses.length,4);});
test('crossing exact 80% emits once, over emits again, reductions do not emit',()=>{const a=M.defaultState(),b=M.add(a,e('a',4000)),c=M.add(b,e('b',500)),d=M.add(c,e('c',501));assert.deepEqual(M.crossings(a,b,'2026-10-08','meals').map(x=>x.level),['near']);assert.equal(M.crossings(b,c,'2026-10-08','meals').length,0);assert.deepEqual(M.crossings(c,d,'2026-10-08','meals').map(x=>x.level),['over']);assert.equal(M.crossings(d,b,'2026-10-08','meals').length,0);});
test('monthly and daily can both cross and direct overshoot emits over',()=>{let a=M.defaultState();a=M.add(a,e('yesterday',119000,'2026-10-07'));const b=M.add(a,e('today',6000));assert.deepEqual(M.crossings(a,b,'2026-10-08','meals').map(x=>[x.scope,x.level]),[['monthly','near'],['daily','over']]);});
test('edit moving date or category checks target totals',()=>{let a=M.add(M.defaultState(),e('a',4000,'2026-10-07'));let b=M.update(a,'a',e('a',4000));assert.equal(M.crossings(a,b,'2026-10-08','meals').length,1);a.settings.daily.transport=5000;b=M.update(a,'a',e('a',4000,'2026-10-08','transport'));assert.equal(M.crossings(a,b,'2026-10-08','transport').length,1);});
test('decimal amounts use integer cents without float accumulation',()=>{assert.equal(M.cents('0.10')+M.cents('0.20'),30);assert.equal(M.cents(' 20.99 '),2099);for(const x of ['-1','1.001','1e4','Infinity','NaN','','.1','1,000'])assert.throws(()=>M.cents(x));});
test('date validation handles leap years and impossible dates',()=>{assert.equal(M.validDate('2024-02-29'),true);for(const d of ['2025-02-29','2026-04-31','2026-13-01','2026-1-1','1800-01-01'])assert.equal(M.validDate(d),false);});
test('persistence round trip and corrupt data is not overwritten',()=>{let value=null;const storage={getItem:()=>value,setItem:(k,v)=>{assert.equal(k,M.KEY);value=v;}};assert.deepEqual(M.load(storage),M.defaultState());const s=M.add(M.defaultState(),{...e('a',1234),note:'<script>test</script>'});M.save(storage,s);assert.deepEqual(M.load(storage),s);value='broken';assert.throws(()=>M.load(storage));assert.equal(value,'broken');});
test('reject malformed backups, duplicate IDs and invalid budgets',()=>{const good=M.add(M.defaultState(),e('a',1));const variants=[{...good,version:6},{...good,expenses:[e('a',-1)]},{...good,expenses:[e('a',1),e('a',2)]},{...good,expenses:[e('a',1,'2026-02-30')]},{...good,expenses:[e('a',1,'2026-10-08','bogus')]},{...good,expenses:[{...e('a',1),note:'x'.repeat(201)}]}];for(const bad of variants)assert.throws(()=>M.validate(bad));const zero=structuredClone(good);zero.settings.daily.meals=0;assert.throws(()=>M.validate(zero));const missing=structuredClone(good);delete missing.settings.monthly.rent;assert.throws(()=>M.validate(missing));assert.throws(()=>M.parse('{'));assert.throws(()=>M.parse('null'));});
test('validation canonicalizes fields and returns independent state',()=>{const good=M.defaultState();good.extra='discard';const clean=M.validate(good);assert.equal(clean.extra,undefined);clean.settings.monthly.meals=0;assert.equal(good.settings.monthly.meals,150000);});
test('aggregate monthly threshold emits at 80%, then only above 100%',()=>{let a=M.defaultState();const categories=M.CATEGORIES;for(const c of categories)a=M.add(a,e(c.id,Math.round(c.budget*100*.79),'2026-10-08',c.id));let b=M.add(a,e('jump',8600,'2026-10-08','rent'));assert.ok(M.crossings(a,b,'2026-10-08','rent').some(x=>x.scope==='total'&&x.level==='near'));let c=M.add(b,e('over',200000,'2026-10-08','rent'));assert.ok(M.crossings(b,c,'2026-10-08','rent').some(x=>x.scope==='total'&&x.level==='over'));});

test('v1 migration preserves settings and every original record',()=>{const old={version:1,settings:{monthly:{rent:1,transport:2,meals:3,dining:4,fun:5},daily:{rent:null,transport:12,meals:5000,dining:null,fun:null}},expenses:[e('legacy',1234)]};const next=M.parse(JSON.stringify(old));assert.equal(next.version,5);assert.deepEqual(next.settings.monthly,old.settings.monthly);assert.deepEqual(next.settings.daily,old.settings.daily);for(const key of Object.keys(old.expenses[0]))assert.equal(next.expenses[0][key],old.expenses[0][key]);assert.equal(next.expenses[0].type,'expense');assert.equal(old.version,1);});
test('income and repayments do not consume budgets; refunds reduce expense without income',()=>{let s=M.defaultState();for(const [id,type,amount,category]of [['expense','expense',10000,'meals'],['income','income',20000,'工资'],['refund','refund',2000,'meals'],['repayment','repayment',9000,'还款'],['transfer','transfer',8000,'转账']])s=M.add(s,{...e(id,amount,'2026-10-08',category),type,source:'测试'});assert.deepEqual(M.totals(s,'2026-10'),{expense:8000,income:20000,net:12000});assert.equal(M.total(s,'2026-10','meals'),8000);assert.deepEqual(M.parse(JSON.stringify(s)),s);});
test('recognition review never writes, flags duplicates and malformed candidates',()=>{const state=M.add(M.defaultState(),{...e('existing',1234),note:'商店'});const payload={records:[{date:'2026-10-08',type:'expense',category:'meals',amount:'12.34',note:'商店'},{date:'2026-10-08',type:'income',category:'工资',amount:'100',note:'公司'},{date:'2026-10-08',type:'income',category:'工资',amount:'100',note:'公司'},{date:'',type:'',category:'meals',amount:'-1'}]};const rows=M.reviewRecognition(payload,state);assert.equal(state.expenses.length,1);assert.equal(rows[0].duplicate,true);assert.equal(rows[0].selected,false);assert.equal(rows[1].selected,true);assert.equal(rows[2].duplicate,true);assert.ok(rows[3].error);assert.equal(rows[3].selected,false);const imported=M.importReviewed(state,rows);assert.equal(imported.expenses.length,2);assert.equal(M.totals(imported,'2026-10').income,10000);assert.equal(state.expenses.length,1);});
test('review rejects invalid amounts and unknown type at commit, transactionally',()=>{for(const amount of ['-1','0','1.001','NaN','Infinity','1e3']){const state=M.defaultState(),row={date:'2026-10-08',type:'expense',category:'meals',amount,note:'',source:'',selected:true};assert.ok(M.reviewRecognition([row],state)[0].error);assert.throws(()=>M.importReviewed(state,[row]));assert.equal(state.expenses.length,0);}assert.throws(()=>M.importReviewed(M.defaultState(),[{date:'2026-10-08',type:'',category:'meals',amount:'1',note:'',source:'',selected:true}]));});
test('income labels are customizable; old labels retained on old records',()=>{let s=M.defaultState();s.settings.incomeLabels=['咨询服务','租金收入'];s=M.add(s,{...e('income',123,'2026-10-08','旧收入分类'),type:'income',source:'客户'});assert.deepEqual(M.validate(s).settings.incomeLabels,['咨询服务','租金收入']);assert.equal(s.expenses[0].category,'旧收入分类');});

test('same day amount type stays duplicate with OCR merchant differences',()=>{const s=M.add(M.defaultState(),{...e('old',2000),note:'星巴克'});const rows=M.reviewRecognition([{date:'2026-10-08',type:'expense',category:'dining',amount:'20.00',note:'星巴尧'}],s);assert.equal(rows[0].duplicate,true);assert.equal(rows[0].selected,false);});
test('refund deletion and changing refund to expense can cross thresholds',()=>{let base=M.add(M.defaultState(),e('expense',5000));base=M.add(base,{...e('refund',2000),type:'refund'});const removed=M.remove(base,'refund');assert.deepEqual(M.crossings(base,removed,'2026-10-08','meals').map(x=>x.level),['near']);const changed=M.update(base,'refund',{...e('refund',2000),type:'expense'});assert.deepEqual(M.crossings(base,changed,'2026-10-08','meals').map(x=>x.level),['over']);const batch=M.importReviewed(M.defaultState(),[{date:'2026-10-08',type:'expense',category:'meals',amount:'50.01',note:'午餐',source:'截图',selected:true}]);assert.deepEqual(M.crossings(M.defaultState(),batch,'2026-10-08','meals').map(x=>x.level),['over']);});

test('OCR dates normalize calendar formats and ISO timestamps without timezone shifts',()=>{for(const date of ['2026-10-08','2026-10-8','2026/10/08','2026.10.8','2026年10月8日','2026-10-08T00:05:00+08:00','2026-10-08T23:59:00Z',' 2026/10/8 '])assert.equal(M.normalizeDate(date),'2026-10-08',date);for(const date of ['2026-02-29','2024-02-30','2026/4/31','2026-13-01','2026-00-08','1899-10-08','2200-01-01','yesterday','08/10/26','2026-10-08junk','2026-10-08T99:00:00Z',null])assert.throws(()=>M.normalizeDate(date),undefined,String(date));assert.equal(M.normalizeDate('2024年2月29日'),'2024-02-29');});
test('standalone normalizer requires reference year and validates leap dates',()=>{for(const date of ['10-8','10/08','10月8日']){assert.throws(()=>M.normalizeDate(date),/缺少年份/);assert.equal(M.normalizeDate(date,'2025'),'2025-10-08');}assert.throws(()=>M.normalizeDate('02-29',2025),/不存在/);assert.equal(M.normalizeDate('02-29',2024),'2024-02-29');assert.throws(()=>M.normalizeDate('10-08','99'),/年份/);assert.equal(M.normalizeDate('2026-12-31',2024),'2026-12-31');});
test('plain objects and native JSON strings use the same normalized review and commit pipeline',()=>{const state=M.defaultState(),payload={records:[{date:'2026/10/8',rawDate:'2026年10月8日',type:'expense',category:'meals',amount:'20.50',note:'午餐',source:'截图'}]};const objects=M.reviewRecognition(payload,state),json=M.reviewRecognition(JSON.stringify(payload),state);assert.deepEqual(json,objects);assert.equal(json[0].date,'2026-10-08');assert.equal(json[0].rawDate,'2026年10月8日');assert.equal(json[0].error,'');assert.equal(json[0].selected,true);const next=M.importReviewed(state,json);assert.equal(next.expenses[0].date,'2026-10-08');assert.equal(next.expenses[0].amount,2050);assert.equal(next.expenses[0].rawDate,undefined);assert.equal(state.expenses.length,0);});
test('unknown values yield field-specific errors rather than generic record error',()=>{const row=M.reviewRecognition(JSON.stringify({records:[{date:'unknown',type:'unknown',category:'',amount:'???'}]}),M.defaultState())[0];assert.equal(row.selected,false);assert.match(row.error,/日期/);assert.match(row.error,/类型/);assert.match(row.error,/分类/);assert.match(row.error,/金额/);assert.doesNotMatch(row.error,/账目数据无效/);});
test('duplicate detection uses canonical dates across existing and imported records',()=>{const state=M.add(M.defaultState(),e('old',2000));const rows=M.reviewRecognition({records:[{date:'2026/10/8',type:'expense',category:'meals',amount:20},{date:'2026年10月8日',type:'expense',category:'meals',amount:21},{date:'2026-10-08T12:00:00Z',type:'expense',category:'meals',amount:21}]},state);assert.deepEqual(rows.map(x=>x.duplicate),[true,false,true]);assert.deepEqual(rows.map(x=>x.selected),[false,true,false]);});
test('edited missing-year and cross-year rows commit exact chosen canonical dates',()=>{const state=M.defaultState();const initial=M.reviewRecognition(JSON.stringify([{date:'12-31',type:'expense',category:'meals',amount:'10'},{date:'01/01',type:'expense',category:'meals',amount:'11'}]),state);assert.ok(initial.every(r=>!r.error&&r.selected));assert.deepEqual(initial.map(r=>r.date),['2026-12-31','2026-01-01']);state.settings.statementYear=2025;const resolved=M.reviewRecognition(initial,state,2025);assert.deepEqual(resolved.map(r=>r.date),['2025-12-31','2025-01-01']);resolved[1].date='2026/1/1';const edited=M.reviewRecognition(resolved,state);assert.ok(edited.every(r=>!r.error));const next=M.importReviewed(state,edited);assert.deepEqual(next.expenses.map(r=>r.date),['2025-12-31','2026-01-01']);assert.deepEqual(M.parse(JSON.stringify(next)),next);});
test('batch validation is atomic and leaves storage untouched until whole batch succeeds',()=>{const state=M.defaultState(),before=JSON.stringify(state);const good={date:'2026/10/8',type:'expense',category:'meals',amount:'10',selected:true},bad={...good,date:'2026/2/30'};let writes=0;const storage={getItem:()=>null,setItem:()=>writes++};assert.throws(()=>M.save(storage,M.importReviewed(state,[good,bad])),/日期/);assert.equal(writes,0);assert.equal(JSON.stringify(state),before);M.save(storage,M.importReviewed(state,[good]));assert.equal(writes,1);});
test('initial OCR ingestion hydrates blank date from rawDate exactly once',()=>{const state=M.defaultState(),payload=JSON.stringify({records:[{date:'',rawDate:'10-08',type:'expense',category:'meals',amount:'10'}]});const initial=M.reviewRecognition(payload,state,undefined,true);assert.equal(initial[0].date,'2026-10-08');assert.equal(initial[0].error,'');const applied=M.reviewRecognition(initial,state,2025);assert.equal(applied[0].date,'2025-10-08');assert.equal(applied[0].error,'');applied[0].date='';const cleared=M.reviewRecognition(applied,state,2025);assert.equal(cleared[0].date,'');assert.match(cleared[0].error,/日期为空/);assert.equal(cleared[0].rawDate,'10-08');assert.throws(()=>M.importReviewed(state,[{...cleared[0],selected:true}]),/日期为空/);assert.throws(()=>M.reviewRecognition(JSON.stringify({records:[]}),state,undefined,true));});

test('statement year defaults to fixed 2026 for new, v1 and older v2 data and persists edits',()=>{
 const state=M.defaultState();assert.equal(state.settings.statementYear,2026);
 for(const version of [1,2]){const old=structuredClone(state);old.version=version;delete old.settings.statementYear;assert.equal(M.parse(JSON.stringify(old)).settings.statementYear,2026);}
 state.settings.statementYear=2025;let saved=null;const storage={getItem:()=>saved,setItem:(k,v)=>saved=v};M.save(storage,state);assert.equal(M.load(storage).settings.statementYear,2025);
 for(const value of [null,'2025',2025.1,1899,2200])assert.throws(()=>M.validate({...state,settings:{...state.settings,statementYear:value}}),/年份/);
});
test('local year completes OCR and reapplies only inferred dates while manual overrides survive',()=>{
 const state=M.defaultState(),candidate=date=>({date,type:'expense',category:'meals',amount:'10'});
 let rows=M.reviewRecognition([candidate('10月8日'),candidate('2024-10-08'),candidate('12-31')],state,undefined,true);
 assert.deepEqual(rows.map(r=>r.date),['2026-10-08','2024-10-08','2026-12-31']);assert.equal(rows[0].rawDate,'10月8日');
 rows[2].date='2023/12/31';state.settings.statementYear=2025;rows=M.reviewRecognition(rows,state,2025);
 assert.deepEqual(rows.map(r=>r.date),['2025-10-08','2024-10-08','2023-12-31']);assert.equal(rows[2].inferredDateSource,undefined);
 const imported=M.importReviewed(state,rows);assert.deepEqual(imported.expenses.map(r=>r.date),rows.map(r=>r.date));assert.equal(imported.expenses[0].inferredDateSource,undefined);
 state.settings.statementYear=2024;rows=M.reviewRecognition(rows,state,2024);assert.equal(rows[0].date,'2024-10-08');assert.equal(rows[2].date,'2023-12-31');
});
test('inferred leap dates invalidate and recover with local year; empty and impossible dates stay errors',()=>{
 const state=M.defaultState(),candidate=date=>({date,type:'expense',category:'meals',amount:'10'});state.settings.statementYear=2024;
 let rows=M.reviewRecognition([candidate('02-29'),candidate('2024-02-29'),candidate('04-31'),candidate('')],state,undefined,true);
 assert.equal(rows[0].date,'2024-02-29');assert.equal(rows[2].selected,false);assert.match(rows[3].error,/日期为空/);
 state.settings.statementYear=2025;rows=M.reviewRecognition(rows,state,2025);assert.match(rows[0].error,/不存在/);assert.equal(rows[1].date,'2024-02-29');assert.equal(rows[1].error,'');
 state.settings.statementYear=2024;rows=M.reviewRecognition(rows,state,2024);assert.equal(rows[0].date,'2024-02-29');assert.equal(rows[0].error,'');rows[0].date='';rows=M.reviewRecognition(rows,state,2024);assert.match(rows[0].error,/日期为空/);assert.equal(rows[0].inferredDateSource,undefined);
});
