'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const base=path.resolve(__dirname,'../app/src/main/assets');
function setup(html='<label>分类<select id="category"><option value="a">餐饮</option><option value="b" disabled>禁用</option><option value="c">交通</option></select></label>'){
 const dom=new JSDOM(html,{url:'https://app.local/',runScripts:'outside-only'}),w=dom.window,d=w.document;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
 w.eval(fs.readFileSync(path.join(base,'select-sheet.js'),'utf8'));
 return {w,d,select:d.querySelector('select'),button:()=>d.querySelector('.select-trigger'),list:()=>d.querySelector('.select-options'),key:key=>d.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true})),tick:()=>new Promise(r=>w.setTimeout(r,0)),close:()=>w.close()};
}
test('native controls remain usable but custom trigger opens named modal and commits input/change once',()=>{const e=setup();try{let input=0,change=0;e.select.addEventListener('input',()=>input++);e.select.addEventListener('change',()=>change++);assert.equal(e.select.tabIndex,-1);assert.equal(e.select.getAttribute('aria-hidden'),'true');assert.match(e.button().getAttribute('aria-label'),/分类：餐饮/);e.button().click();assert.equal(e.w.SelectSheet.isOpen(),true);assert.equal(e.d.activeElement,e.list());assert.equal(e.button().getAttribute('aria-expanded'),'true');e.d.querySelector('[data-index="2"]').click();assert.equal(e.select.value,'c');assert.equal(input,1);assert.equal(change,1);assert.equal(e.d.activeElement,e.button());assert.equal(e.w.SelectSheet.isOpen(),false);assert.match(e.button().textContent,/交通/);}finally{e.close();}});
test('keyboard navigation skips disabled options; Home/End select; Escape, cancel, Back never mutate',()=>{const e=setup();try{let change=0;e.select.addEventListener('change',()=>change++);e.button().click();e.key('ArrowDown');assert.equal(e.list().getAttribute('aria-activedescendant'),'select-sheet-option-2');e.key('Escape');assert.equal(e.select.value,'a');e.button().click();e.key('End');e.d.querySelector('.select-sheet-cancel').click();assert.equal(e.select.value,'a');e.button().click();e.key('End');assert.equal(e.w.SelectSheet.close(),true);assert.equal(e.w.SelectSheet.close(),false);assert.equal(e.select.value,'a');e.button().click();e.key('End');e.key('Home');e.key('Enter');assert.equal(change,0);e.button().click();e.key('End');e.key('Enter');assert.equal(e.select.value,'c');assert.equal(change,1);}finally{e.close();}});
test('programmatic values and option selected changes update trigger without synthetic events',()=>{const e=setup();try{let changed=0;e.select.addEventListener('change',()=>changed++);e.select.value='c';assert.match(e.button().textContent,/交通/);e.select.options[0].selected=true;assert.match(e.button().textContent,/餐饮/);e.select.selectedIndex=2;assert.match(e.button().textContent,/交通/);assert.equal(changed,0);}finally{e.close();}});
test('dynamic review selectors, rebuilt filter options, option labels and disabled state stay in sync',async()=>{const e=setup();try{const host=e.d.createElement('div');host.innerHTML='<label>筛选分类<select id="filter"><option value="">全部分类</option></select></label><label>识别类型<select data-field="type"><option>支出</option><option>收入</option></select></label>';e.d.body.append(host);await e.tick();assert.equal(e.d.querySelectorAll('.select-trigger').length,3);const filter=e.d.getElementById('filter');filter.innerHTML='<option value="a">餐饮</option><option value="c">交通</option>';filter.value='c';await e.tick();assert.match(filter.nextElementSibling.textContent,/交通/);filter.options[1].firstChild.data='通勤';await e.tick();assert.match(filter.nextElementSibling.textContent,/通勤/);filter.nextElementSibling.click();filter.options[1].disabled=true;await e.tick();assert.equal(e.d.querySelector('[data-index="1"]').getAttribute('aria-disabled'),'true');filter.disabled=true;await e.tick();assert.equal(filter.nextElementSibling.disabled,true);assert.equal(e.w.SelectSheet.isOpen(),false);host.remove();await e.tick();assert.equal(e.d.querySelectorAll('.select-trigger').length,1);}finally{e.close();}});
test('empty or fully disabled select cannot open; form reset and fieldset disabled mirror',async()=>{const e=setup('<form><fieldset><label>单位<select><option value="a">kJ</option><option value="b">kcal</option></select></label></fieldset></form>');try{e.select.value='b';e.d.querySelector('form').reset();await e.tick();assert.match(e.button().textContent,/kJ/);e.d.querySelector('fieldset').disabled=true;await e.tick();assert.equal(e.button().disabled,true);e.d.querySelector('fieldset').disabled=false;e.select.replaceChildren();await e.tick();assert.equal(e.button().disabled,true);e.button().click();assert.equal(e.w.SelectSheet.isOpen(),false);e.select.innerHTML='<option disabled>无可用选项</option>';await e.tick();assert.equal(e.button().disabled,true);e.select.options[0].disabled=false;await e.tick();assert.equal(e.button().disabled,false);}finally{e.close();}});
test('repeated init/open/cancel uses one sheet and never duplicates change handlers; focus trap stays inside',()=>{const e=setup();try{let changed=0;e.select.addEventListener('change',()=>changed++);for(let i=0;i<20;i++){e.w.SelectSheet.init();e.button().click();e.key('Tab');assert.equal(e.d.activeElement,e.d.querySelector('.select-sheet-cancel'));e.key('Tab');assert.equal(e.d.activeElement,e.list());e.key('Escape');}assert.equal(e.d.querySelectorAll('#select-sheet').length,1);assert.equal(e.d.querySelectorAll('.select-trigger').length,1);e.button().click();e.key('End');e.key('Enter');assert.equal(changed,1);}finally{e.close();}});
test('real app static/dynamic selectors and Back preserve parent dialog and unsaved draft',async()=>{const e=setup(fs.readFileSync(path.join(base,'index.html'),'utf8'));try{e.w.scrollTo=()=>{};e.w.alert=()=>{};e.w.confirm=()=>true;e.w.setInterval=()=>0;e.w.eval(fs.readFileSync(path.join(base,'model.js'),'utf8'));e.w.eval(fs.readFileSync(path.join(base,'app.js'),'utf8'));await e.tick();e.d.querySelector('[data-action="add"]').click();e.d.getElementById('amount').value='77';const type=e.d.getElementById('type');type.nextElementSibling.click();assert.equal(e.w.handleBack(),true);assert.equal(e.w.SelectSheet.isOpen(),false);assert.equal(e.d.getElementById('expense-dialog').open,true);assert.equal(e.d.getElementById('amount').value,'77');type.nextElementSibling.click();e.d.querySelector('[data-index="1"]').click();await e.tick();assert.equal(type.value,'income');assert.match(e.d.getElementById('category').nextElementSibling.textContent,/工资/);assert.equal(e.d.querySelectorAll('select').length,e.d.querySelectorAll('.select-trigger').length);}finally{e.close();}});
test('actual recognition rows rebuild type/category selectors and filter selection stays programmatically synchronized',async()=>{const e=setup(fs.readFileSync(path.join(base,'index.html'),'utf8'));try{e.w.scrollTo=()=>{};e.w.alert=message=>{throw Error(message);};e.w.confirm=()=>true;e.w.setInterval=()=>0;e.w.eval(fs.readFileSync(path.join(base,'model.js'),'utf8'));e.w.eval(fs.readFileSync(path.join(base,'app.js'),'utf8'));e.w.receiveRecognition(JSON.stringify({records:[{date:'2026-10-08',type:'expense',category:'meals',amount:'20.83',note:'合成交易',source:'测试'}]}));await e.tick();let type=e.d.querySelector('#review-list [data-field="type"]'),category=e.d.querySelector('#review-list [data-field="category"]');assert.match(category.nextElementSibling.textContent,/日常吃饭/);type.nextElementSibling.click();const income=Array.from(type.options).findIndex(option=>option.value==='income');e.d.querySelector('[data-index="'+income+'"]').click();await e.tick();assert.equal(type.value,'income');assert.match(category.nextElementSibling.textContent,/工资/);assert.equal(e.w.localStorage.getItem(e.w.BudgetModel.KEY),null);category.nextElementSibling.click();assert.equal(e.w.handleBack(),true);assert.equal(e.d.getElementById('review-dialog').open,true);e.w.receiveRecognition(JSON.stringify({records:[{date:'2026-10-09',type:'expense',category:'meals',amount:'10',note:'第二次',source:'测试'}]}));await e.tick();assert.equal(e.d.querySelectorAll('#review-list .select-trigger').length,2);const filter=e.d.getElementById('filter');filter.value='meals';assert.match(filter.nextElementSibling.textContent,/日常吃饭/);assert.equal(e.d.querySelectorAll('select').length,e.d.querySelectorAll('.select-trigger').length);}finally{e.close();}});
