'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('../tools/dom-test/node_modules/jsdom');
const source=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/theme.js'),'utf8');
function setup(){const dom=new JSDOM('<!doctype html><html><body><section id="settings"><h2>设置</h2><form id="settings-form"></form></section></body></html>',{runScripts:'outside-only'});dom.window.eval(source);let colors={budget:'#527BA8',food:'#398A83'},mode='budget',fail=false,calls=0;const ui=dom.window.ThemeUI;const api={get:()=>colors,getMode:()=>mode,save:value=>{calls++;if(fail)return false;colors=value;return true;}};ui.init(api);return {dom,ui,api,doc:dom.window.document,get colors(){return colors;},get calls(){return calls;},setMode(v){mode=v;ui.sync(colors,mode);},fail(){fail=true;}};}
test('theme injects two named independent palettes and initializes once',()=>{const t=setup();t.ui.init(t.api);assert.equal(t.doc.querySelectorAll('#theme-settings').length,1);assert.equal(t.doc.querySelectorAll('.theme-swatch').length,10);assert.equal(t.doc.querySelectorAll('.theme-swatch[aria-pressed=true]').length,2);assert.equal(t.doc.querySelectorAll('input[type=color]').length,0);assert.equal(t.doc.querySelector('#settings-form #theme-settings'),null);t.doc.querySelector('[data-theme-mode=food][data-theme-color="#66845C"]').click();assert.equal(t.colors.food,'#66845C');assert.equal(t.colors.budget,'#527BA8');assert.equal(t.doc.documentElement.style.getPropertyValue('--accent'),'#527BA8');t.setMode('food');assert.equal(t.doc.documentElement.style.getPropertyValue('--accent'),'#66845C');assert.equal(t.doc.documentElement.dataset.mode,'food');t.dom.window.close();});
test('custom hex rejects malformed values, accepts case-insensitive six digits',()=>{const t=setup(),input=t.doc.querySelector('#theme-hex-budget'),button=t.doc.querySelector('[aria-label="应用预算自定义颜色"]');for(const value of ['red','#fff','123456','#12345G','url(x)','']){input.value=value;button.click();assert.equal(t.calls,0);assert.equal(input.getAttribute('aria-invalid'),'true');}input.value='#aAcCeE';button.click();assert.equal(t.colors.budget,'#AACCEE');assert.equal(t.colors.food,'#398A83');assert.equal(input.getAttribute('aria-invalid'),null);assert.equal(t.doc.querySelectorAll('[data-theme-mode=budget][aria-pressed=true]').length,0);assert.match(t.doc.querySelector('#theme-status').textContent,/已保存/);t.dom.window.close();});
test('save failure never applies unpersisted theme',()=>{const t=setup();t.fail();t.doc.querySelector('[data-theme-mode=budget][data-theme-color="#A3637B"]').click();assert.equal(t.colors.budget,'#527BA8');assert.equal(t.doc.documentElement.style.getPropertyValue('--accent'),'#527BA8');assert.match(t.doc.querySelector('#theme-status').textContent,/未保存/);t.dom.window.close();});
test('preset and arbitrary light and dark colors preserve AA text contrast',()=>{const t=setup();for(let r=0;r<256;r+=17)for(let g=0;g<256;g+=17)for(let b=0;b<256;b+=17){const hex='#'+[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join(''),p=t.ui.palette(hex);assert.ok(t.ui.contrast(p.accent,p.on)>=4.5,hex+' button');assert.ok(t.ui.contrast(p.ink,p.soft)>=4.5,hex+' soft');assert.ok(t.ui.contrast(p.ink,'#F5F8FC')>=4.5,hex+' canvas');}t.dom.window.close();});
test('invalid restored colors fall back safely and sync leaves focused typing alone',()=>{const t=setup(),input=t.doc.querySelector('#theme-hex-budget');input.focus();input.value='#112';t.ui.sync({budget:'red',food:'#aabbcc'},'food');assert.equal(input.value,'#112');assert.equal(t.doc.documentElement.style.getPropertyValue('--budget-accent'),'#527BA8');assert.equal(t.doc.documentElement.style.getPropertyValue('--accent'),'#AABBCC');t.dom.window.close();});
