'use strict';
// Independent integration checks load the real application scripts, using synthetic data only.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const base=path.resolve(__dirname,'../app/src/main/assets'),M=require('../app/src/main/assets/model.js');
function setup(saved){
 const dom=new JSDOM(fs.readFileSync(path.join(base,'index.html'),'utf8'),{url:'https://app.local/',runScripts:'outside-only'}),w=dom.window,calls=[];
 w.scrollTo=()=>{};w.alert=text=>calls.push(['alert',text]);w.confirm=()=>true;w.setInterval=()=>0;
 w.Android={notify:()=>{},captureFoodPhoto:(...args)=>calls.push(['camera',...args]),chooseFoodPhoto:(...args)=>calls.push(['gallery',...args]),checkForUpdates:()=>calls.push(['updates']),exportBackup:text=>calls.push(['export',text])};
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
 if(saved!==undefined)w.localStorage.setItem(M.KEY,typeof saved==='string'?saved:JSON.stringify(saved));
 for(const name of ['model.js','theme.js','wellness.js','app.js','select-sheet.js'])w.eval(fs.readFileSync(path.join(base,name),'utf8'));
 const $=id=>w.document.getElementById(id);
 return {w,$,calls,state:()=>JSON.parse(w.localStorage.getItem(M.KEY)),raw:()=>w.localStorage.getItem(M.KEY),input:(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('input',{bubbles:true}));},change:(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));},submit:id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})),tick:()=>new Promise(r=>w.setTimeout(r,0)),close:()=>w.close()};
}
function fixture(){let s=M.defaultState();s=M.add(s,{id:'ledger',date:'2026-10-08',type:'income',category:'工资',amount:123400,note:'合成工资',source:'合成来源'});s=M.addNutrition(s,{id:'meal',date:'2026-10-08',name:'合成午餐',grams:100,kcal:250,lowKcal:200,highKcal:300,note:'合成测试'});s=M.addFavorite(s,{id:'favorite',name:'合成常用食物',grams:100,lowKcal:200,highKcal:300,note:''});return s;}
test('four wellness routes and budget switching never mutate saved history',()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();assert.equal(e.w.WellnessUI.currentRoute,'today');for(const route of ['log','progress','plan','today']){e.w.document.querySelector('#wellness-nav [data-wellness-route='+route+']').click();assert.equal(e.w.WellnessUI.currentRoute,route);for(const other of ['today','log','progress','plan'])assert.equal(e.$('wellness-'+other).hidden,other!==route);assert.equal(e.w.document.querySelectorAll('#wellness-nav [aria-current=page]').length,1);}assert.equal(e.w.WellnessUI.route('unknown'),false);e.$('mode-budget').click();assert.equal(e.$('budget-nav').hidden,false);e.$('mode-food').click();assert.equal(e.raw(),before);}finally{e.close();}});
test('nested profile selector Back restores draft, then profile Back cancels with no implicit profile',async()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();e.w.WellnessUI.route('plan');e.$('edit-profile').click();e.input('profile-age','45');e.$('profile-method').nextElementSibling.click();assert.equal(e.w.SelectSheet.isOpen(),true);assert.equal(e.w.handleBack(),true);assert.equal(e.w.SelectSheet.isOpen(),false);assert.equal(e.$('profile-dialog').open,true);assert.equal(e.$('profile-age').value,'45');assert.equal(e.w.document.activeElement,e.$('profile-method').nextElementSibling);assert.equal(e.w.handleBack(),true);assert.equal(e.$('profile-dialog').open,false);assert.equal(e.raw(),before);assert.equal(e.state().profile,null);await e.tick();}finally{e.close();}});
test('camera and gallery receive no profile/history arguments; cancelled photo review saves nothing',()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();e.$('capture-food').click();e.$('choose-food').click();assert.deepEqual(e.calls,[['camera'],['gallery']]);e.w.receiveFoodRecognition(JSON.stringify({name:'合成照片食物',portionGrams:100,caloriesLow:100,caloriesHigh:200,confidence:'low',note:'仅供测试'}));assert.equal(e.$('food-dialog').open,true);assert.equal(e.w.handleBack(),true);assert.equal(e.$('food-dialog').open,false);assert.equal(e.raw(),before);}finally{e.close();}});
test('favorite relog requires save, repeated submit appends only once and original history stays unchanged',()=>{const initial=fixture(),e=setup(initial);try{e.$('mode-food').click();e.w.WellnessUI.route('log');e.w.document.querySelector('[data-favorite-use]').click();e.input('food-grams','50');assert.equal(e.state().nutrition.length,1);e.submit('food-form');e.submit('food-form');assert.equal(e.state().nutrition.length,2);assert.equal(e.state().nutrition.at(-1).grams,50);assert.equal(e.state().nutrition.at(-1).lowKcal,100);assert.deepEqual(e.state().nutrition[0],initial.nutrition[0]);assert.deepEqual(e.state().favorites,initial.favorites);assert.deepEqual(e.state().expenses,initial.expenses);}finally{e.close();}});
const plan={method:'manual',adultEligible:true,sex:'male',exerciseMode:'included',exerciseCredit:0,maintenanceKcal:2000,deficitKcal:0};
test('remaining ring uses selected date, exact estimate range and bounded remaining proportion without writes',()=>{let s=M.setProfile(fixture(),plan);s=M.addNutrition(s,{id:'next',date:'2026-10-09',name:'合成另一日',grams:400,kcal:2300,lowKcal:2200,highKcal:2400,note:''});s=M.addExercise(s,{id:'exercise',date:'2026-10-08',name:'合成运动',activeKcal:300,note:''});const e=setup(s);try{const before=e.raw();e.$('mode-food').click();e.change('food-day','2026-10-08');const r=e.$('wellness-ring');assert.equal(r.dataset.date,'2026-10-08');assert.equal(r.dataset.target,'2000');assert.equal(r.dataset.intakeLow,'200');assert.equal(r.dataset.intakeHigh,'300');assert.equal(r.dataset.remainingLow,'1700');assert.equal(r.dataset.remainingHigh,'1800');assert.equal(Number(r.dataset.progress),.85);assert.equal(Number(r.dataset.upperProgress),.9);assert.match(e.$('wellness-ring-title').textContent,/2026-10-08/);e.change('food-day','2026-10-09');assert.equal(r.dataset.state,'over');assert.equal(r.dataset.remainingLow,'-400');assert.equal(r.dataset.remainingHigh,'-200');assert.equal(r.dataset.progress,'0');assert.equal(r.dataset.upperProgress,'0');assert.match(e.$('wellness-ring-value').textContent,/-400/);assert.equal(e.raw(),before);}finally{e.close();}});
test('crossing-budget estimate and zero target ring avoid misleading positive or nonfinite fill',()=>{let s=M.setProfile(M.defaultState(),plan);s=M.addNutrition(s,{id:'range',date:'2026-10-08',name:'合成区间',grams:100,kcal:1950,lowKcal:1800,highKcal:2100,note:''});const e=setup(s);try{e.$('mode-food').click();e.change('food-day','2026-10-08');const r=e.$('wellness-ring');assert.equal(r.dataset.state,'uncertain');assert.equal(r.dataset.progress,'0');assert.equal(Number(r.dataset.upperProgress),.1);const zero=e.w.WellnessUI.ringModel({ready:true,targetKcal:0,remainingLow:-100,remainingHigh:0});assert.equal(zero.state,'unavailable');assert.equal(zero.progress,null);assert.equal(zero.upperProgress,null);for(const target of [-1,-100])assert.equal(e.w.WellnessUI.ringModel({ready:true,targetKcal:target,remainingLow:-10,remainingHigh:10}).progress,null);}finally{e.close();}});
test('clearing profile removes stale ring numbers and never deletes meals or exercises',()=>{const s=M.setProfile(fixture(),plan),e=setup(s);try{e.$('mode-food').click();e.change('food-day','2026-10-08');assert.equal(e.$('wellness-ring').dataset.target,'2000');e.w.WellnessUI.route('plan');e.$('edit-profile').click();e.$('clear-profile').click();assert.equal(e.state().profile,null);assert.deepEqual(e.state().nutrition,s.nutrition);assert.deepEqual(e.state().expenses,s.expenses);const r=e.$('wellness-ring');assert.equal(r.dataset.state,'empty');assert.equal(r.dataset.target,undefined);assert.equal(r.dataset.progress,undefined);assert.equal(e.$('wellness-ring-fill').getAttribute('stroke-dasharray'),'0 100');}finally{e.close();}});
test('settings Back restores originating wellness page and never exits or navigates an invisible page',()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();for(const origin of ['today','plan']){e.w.WellnessUI.route(origin);e.$('wellness-settings').click();assert.equal(e.$('settings').hidden,false);assert.equal(e.$('food').hidden,true);assert.equal(e.w.handleBack(),true);assert.equal(e.$('settings').hidden,true);assert.equal(e.$('food').hidden,false);assert.equal(e.$('wellness-nav').hidden,false);assert.equal(e.$('budget-nav').hidden,true);assert.equal(e.w.WellnessUI.currentRoute,origin);}e.$('wellness-settings').click();e.$('mode-budget').click();e.$('mode-food').click();assert.equal(e.$('settings').hidden,true);assert.equal(e.$('food').hidden,false);assert.equal(e.w.WellnessUI.currentRoute,'today');assert.equal(e.raw(),before);}finally{e.close();}});
test('weight SVG uses chronological true-day spacing, correct kg values and a full text alternative',()=>{let s=fixture();for(const r of [{id:'last',date:'2026-10-11',kg:70},{id:'first',date:'2026-10-01',kg:72},{id:'middle',date:'2026-10-02',kg:71}])s=M.addWeight(s,r);const e=setup(s);try{const before=e.raw();e.$('mode-food').click();e.change('food-day','2026-10-08');assert.equal(e.$('wellness-page-title').textContent,'当日概览');e.w.WellnessUI.route('progress');assert.equal(e.w.document.querySelector('.wellness-date').hidden,true);const svg=e.$('weight-chart').querySelector('svg[role=img]');assert.ok(svg);assert.ok(svg.querySelector('title'));assert.ok(svg.querySelector('desc'));const points=[...svg.querySelectorAll('.wellness-weight-point')];assert.deepEqual(points.map(p=>p.dataset.date),['2026-10-01','2026-10-02','2026-10-11']);assert.deepEqual(points.map(p=>Number(p.dataset.kg)),[72,71,70]);const xs=points.map(p=>Number(p.getAttribute('cx')));assert.ok(Math.abs((xs[1]-xs[0])/(xs[2]-xs[0])-.1)<1e-6);assert.equal(e.$('weight-list').querySelectorAll('button').length,3);e.w.WellnessUI.route('plan');assert.equal(e.w.document.querySelector('.wellness-date').hidden,true);e.w.WellnessUI.route('log');assert.equal(e.w.document.querySelector('.wellness-date').hidden,false);assert.equal(e.raw(),before);}finally{e.close();}});
test('weight chart handles empty, single, identical-date and latest14 without losing older records',()=>{const e=setup(fixture());try{assert.equal(e.$('weight-chart').querySelector('svg'),null);const one=e.w.WellnessUI.weightChartModel([{id:'a',date:'2026-10-01',kg:70}]);assert.equal(one.points[0].x,190);assert.ok(Number.isFinite(one.points[0].y));const same=e.w.WellnessUI.weightChartModel([{id:'b',date:'2026-10-01',kg:70},{id:'a',date:'2026-10-01',kg:70}]);assert.equal(same.points.length,2);for(const p of same.points){assert.equal(p.x,190);assert.ok(Number.isFinite(p.y));}const many=Array.from({length:16},(_,i)=>({id:'w'+i,date:'2026-10-'+String(i+1).padStart(2,'0'),kg:70+i/10}));const chart=e.w.WellnessUI.weightChartModel(many.reverse());assert.equal(chart.points.length,14);assert.equal(chart.points[0].date,'2026-10-03');assert.equal(chart.points.at(-1).date,'2026-10-16');assert.equal(many.length,16);let s=fixture();for(const r of many)s=M.addWeight(s,r);e.w.receiveBackup(JSON.stringify(s));assert.equal(e.$('weight-list').querySelectorAll('button').length,16);assert.equal(e.$('weight-chart').querySelectorAll('.wellness-weight-point').length,14);assert.equal(e.state().weights.length,16);}finally{e.close();}});
test('weight cancellation and repeated closed submit never create unintended entries',()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();e.w.WellnessUI.route('progress');e.$('add-weight').click();e.input('weight-kg','70.25');e.w.handleBack();assert.equal(e.raw(),before);e.submit('weight-form');assert.equal(e.raw(),before);e.$('add-weight').click();e.input('weight-kg','70.25');e.submit('weight-form');e.submit('weight-form');assert.equal(e.state().weights.length,1);assert.equal(e.state().weights[0].kg,70.25);assert.equal(e.$('weight-chart').querySelector('.wellness-weight-line'),null);assert.equal(e.$('weight-chart').querySelectorAll('.wellness-weight-point').length,1);}finally{e.close();}});
test('all wellness dialogs restore visible opener focus on Back and repeated opens preserve drafts',()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();for(const [route,opener,dialog,field]of [['log','add-food','food-dialog','food-name'],['log','add-favorite','favorite-dialog','favorite-name'],['plan','edit-profile','profile-dialog','profile-age'],['today','add-exercise','exercise-dialog','exercise-name'],['progress','add-weight','weight-dialog','weight-kg']]){e.w.WellnessUI.route(route);const button=e.$(opener);button.focus();button.click();e.input(field,'77');button.click();assert.equal(e.$(field).value,'77');assert.equal(e.$(dialog).open,true);assert.equal(e.w.handleBack(),true);assert.equal(e.$(dialog).open,false);assert.equal(e.w.document.activeElement,button);}assert.equal(e.raw(),before);}finally{e.close();}});
test('late photo result requires replacing draft confirmation and keeps route and ledger untouched until save',()=>{const e=setup(fixture());try{e.$('mode-food').click();e.w.WellnessUI.route('log');e.$('add-food').click();e.input('food-name','未保存手填草稿');e.input('food-grams','123');const before=e.raw(),photo=JSON.stringify({name:'迟到的合成估算',portionGrams:150,caloriesLow:200,caloriesHigh:250,confidence:'low',note:''});let asked=0;e.w.confirm=()=>{asked++;return false;};e.w.receiveFoodRecognition(photo);assert.equal(asked,1);assert.equal(e.$('food-name').value,'未保存手填草稿');assert.equal(e.$('food-grams').value,'123');assert.equal(e.raw(),before);e.w.confirm=()=>true;e.w.receiveFoodRecognition(photo);assert.equal(e.$('food-name').value,'迟到的合成估算');assert.equal(e.w.WellnessUI.currentRoute,'log');assert.equal(e.raw(),before);e.w.handleBack();assert.equal(e.raw(),before);}finally{e.close();}});
test('plan onboarding is blank, eligibility-gated and local, with explicit zero deficit preserved',()=>{const initial=fixture(),e=setup(initial);try{e.$('mode-food').click();e.w.WellnessUI.route('plan');assert.equal(e.$('wellness-plan-steps').hidden,false);e.$('edit-profile').click();for(const id of ['profile-age','profile-height','profile-weight','profile-sex','profile-deficit'])assert.equal(e.$(id).value,'');assert.equal(e.$('profile-eligible').checked,false);e.change('profile-method','manual');e.change('profile-sex','male');e.input('profile-maintenance','2000');e.input('profile-deficit','0');e.submit('profile-form');assert.equal(e.state().profile,null);e.$('profile-eligible').checked=true;e.submit('profile-form');assert.equal(e.state().profile.deficitKcal,0);assert.equal(e.state().profile.exerciseMode,'included');assert.equal(e.state().profile.exerciseCredit,0);assert.equal(e.$('wellness-plan-steps').hidden,true);assert.equal(e.$('wellness-plan-summary').hidden,false);assert.deepEqual(e.calls,[]);assert.deepEqual(e.state().expenses,initial.expenses);assert.deepEqual(e.state().nutrition,initial.nutrition);}finally{e.close();}});
test('exercise type shortcuts never invent kcal; dates and duplicate submit remain controlled',()=>{const e=setup(fixture());try{const before=e.raw();e.$('mode-food').click();e.change('food-day','2026-10-08');e.$('add-exercise').click();assert.equal(e.$('exercise-date').value,'2026-10-08');for(const button of e.w.document.querySelectorAll('[data-exercise-name]')){button.click();assert.equal(e.$('exercise-kcal').value,'');assert.equal(e.$('exercise-name').value,button.dataset.exerciseName);}e.submit('exercise-form');assert.equal(e.raw(),before);e.input('exercise-kcal','123.5');e.submit('exercise-form');e.submit('exercise-form');assert.equal(e.state().exercises.length,1);assert.equal(e.state().exercises[0].activeKcal,123.5);assert.equal(e.state().exercises[0].date,'2026-10-08');assert.equal(e.state().profile,null);}finally{e.close();}});
