package cn.dot.budget;
import java.io.*; import java.util.*; import java.util.concurrent.atomic.*;
public class IndependentReview {
 static int n; static void ok(boolean b){n++;if(!b)throw new AssertionError("check "+n);} static void reject(Runnable r){try{r.run();throw new AssertionError("accepted");}catch(IllegalArgumentException good){n++;}}
 static class Store implements AiRememberedConsent.Store {int v;Set<String>s=new HashSet<>();boolean fail;public int version(){return v;}public boolean allowed(String k){return s.contains(k);}public boolean write(String k){if(fail)return false;if(v!=1)s.clear();v=1;s.add(k);return true;}public boolean clear(){if(fail)return false;s.clear();v=0;return true;}public boolean empty(){return s.isEmpty()&&v==0;}}
 static AiRequestContract req(String mode,String source){return new AiRequestContract(1,mode,source,0);}
 public static void main(String[]args)throws Exception {
  Store store=new Store();AiRememberedConsent c=new AiRememberedConsent(store);AiRequestContract fi=req("food","food_image"),fc=req("food","food_camera"),bi=req("budget","statement_image"),ft=new AiRequestContract(1,"food","food_text",0,"x","午餐"),bt=new AiRequestContract(1,"budget","budget_text",0,"y","午餐12元");
  for(AiRequestContract r:new AiRequestContract[]{fi,fc,bi,ft,bt})ok(!c.allows(r));ok(!c.remember(fi,false,c.generation()));ok(!c.allows(fi));ok(c.remember(fi,true,c.generation()));ok(c.allows(fi)&&c.allows(fc));ok(!c.allows(bi)&&!c.allows(ft)&&!c.allows(bt));ok(new AiRememberedConsent(store).allows(fi));ok(c.allows(new AiRequestContract(1,"food","food_image",0,"retry-attempt",null,"failed-request")));
  int old=c.generation();AtomicInteger cancel=new AtomicInteger();ok(c.revoke(cancel::incrementAndGet));ok(cancel.get()==1);ok(!c.allows(fi));ok(!c.remember(fi,true,old));ok(!new AiRememberedConsent(store).allows(fi));store.v=99;store.s.add("food_image");ok(!new AiRememberedConsent(store).allows(fi));ok(c.remember(bi,true,c.generation()));ok(c.allows(bi)&&!c.allows(fi));store.fail=true;ok(!c.remember(fi,true,c.generation()));ok(!c.allows(bi));
  ok(AiBoundedBytes.MAX_BYTES<10_000_000);AiBoundedBytes bytes=new AiBoundedBytes(AiBoundedBytes.MAX_BYTES);bytes.write(new byte[AiBoundedBytes.MAX_BYTES]);ok(bytes.size()==9_999_999);try{bytes.write(1);throw new AssertionError();}catch(IOException expected){ok(bytes.exceeded());}ok(bytes.size()==9_999_999);
  AiRequestSession session=new AiRequestSession();AiRequestSession.Ticket ticket=session.reserve(fi);String payload=AiPayloadBuilder.image(fi,new byte[AiBoundedBytes.MAX_BYTES],"image/jpeg");ok(payload.getBytes("UTF-8").length<=AiPayloadBuilder.MAX_PAYLOAD_BYTES);reject(()->AiPayloadBuilder.image(fi,new byte[10_000_000],"image/jpeg"));try{new AiConsentSnapshot(ticket,new byte[10_000_000],"image/jpeg",b->"x");throw new AssertionError();}catch(IllegalArgumentException expected){n++;}
  int[][] orient={{1,0,0,1},{-1,0,0,1},{-1,0,0,-1},{1,0,0,-1},{0,1,1,0},{0,-1,1,0},{0,-1,-1,0},{0,1,-1,0}};
  for(int i=1;i<=8;i++){float[]m=AiImagePolicy.matrix(i);ok(m[0]==orient[i-1][0]&&m[1]==orient[i-1][1]&&m[3]==orient[i-1][2]&&m[4]==orient[i-1][3]);for(int w:new int[]{1,1024,12000,65535})for(int h:new int[]{1,800,9000,65535}){if((long)w*h>AiImagePolicy.MAX_SOURCE_PIXELS){try{AiImagePolicy.plan(w,h,true,i,8*1024*1024);throw new AssertionError("source pixel cap");}catch(IllegalArgumentException expected){n++;}}else{AiImagePolicy.Plan p=AiImagePolicy.plan(w,h,true,i,8*1024*1024);ok(p.outputWidth<=2048&&p.outputHeight<=2048&&p.estimatedBytes<=8*1024*1024);}}}
  reject(()->AiImagePolicy.plan(1000,10000,false,1,AiImagePolicy.MAX_BITMAP_BUDGET));reject(()->AiImagePolicy.plan(65536,1,true,1,AiImagePolicy.MAX_BITMAP_BUDGET));
  for(long length:new long[]{1,10_000_001,AiSourceCopy.MAX_SOURCE_BYTES,AiSourceCopy.MAX_SOURCE_BYTES+1}){InputStream in=new InputStream(){long left=length;public int read(){throw new AssertionError();}public int read(byte[]b,int off,int len){if(left==0)return -1;int count=(int)Math.min(left,len);left-=count;return count;}};AtomicLong written=new AtomicLong();OutputStream out=new OutputStream(){public void write(int x){throw new AssertionError();}public void write(byte[]b,int off,int len){written.addAndGet(len);}};try{long actual=AiSourceCopy.copy(in,out,()->false);ok(length<=AiSourceCopy.MAX_SOURCE_BYTES&&actual==length);}catch(IOException e){ok(length>AiSourceCopy.MAX_SOURCE_BYTES);}ok(written.get()<=AiSourceCopy.MAX_SOURCE_BYTES);}
  AtomicInteger writes=new AtomicInteger();try{AiSourceCopy.copy(new ByteArrayInputStream(new byte[]{1}),new OutputStream(){public void write(int x){writes.incrementAndGet();}},()->true);throw new AssertionError();}catch(InterruptedIOException e){ok(writes.get()==0);}
  System.out.println("PASS independent review: "+n+" pure-JVM assertions; Android pixel/UI/device paths not executed.");
 }
}
