package cn.dot.budget;
import java.util.*;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;
import java.io.*;
import java.net.*;
/** Independent, pure JVM contract checks. No Android device, network or real credentials. */
public final class AiLifecycleReviewTest {
 private static int assertions;
 private static void check(boolean value){assertions++;if(!value)throw new AssertionError("AI boundary assertion "+assertions);}
 private static void rejects(Runnable action){assertions++;try{action.run();}catch(IllegalArgumentException expected){return;}throw new AssertionError("Accepted invalid AI boundary input "+assertions);}
 private interface CheckedAction{void run()throws Exception;}
 private static void rejectsChecked(CheckedAction action)throws Exception{assertions++;try{action.run();}catch(IllegalArgumentException expected){return;}throw new AssertionError("Accepted invalid AI snapshot "+assertions);}
 private static String repeat(String value,int count){StringBuilder out=new StringBuilder();for(int i=0;i<count;i++)out.append(value);return out.toString();}
 private static Map<String,Object> map(Object... pairs){Map<String,Object> out=new LinkedHashMap<>();for(int i=0;i<pairs.length;i+=2)out.put((String)pairs[i],pairs[i+1]);return out;}
 private static String completion(Object draft){return AiJson.stringify(map("choices",Arrays.asList(map("index",0,"finish_reason","stop","message",map("role","assistant","content",AiJson.stringify(draft))))));}
 private static final class FakeConnection extends HttpURLConnection{
  final ByteArrayOutputStream output=new ByteArrayOutputStream();Runnable beforeOutput;boolean disconnected;int responses,status=200,inputReads;
  FakeConnection(URL url){super(url);}public void connect(){}public void disconnect(){disconnected=true;}public boolean usingProxy(){return false;}
  public OutputStream getOutputStream(){if(beforeOutput!=null)beforeOutput.run();return output;}
  public int getResponseCode(){responses++;return status;}public InputStream getInputStream(){inputReads++;return new ByteArrayInputStream("{}".getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 }
 private static final class FakeKeyStore implements AiKeyDeletion.Store{
  final List<String> events=new ArrayList<>();boolean committed=true,empty=true,absent=true;int fail;
  private void step(String name,int index)throws Exception{check(!events.isEmpty()&&events.get(0).equals("invalidate"));events.add(name);if(fail==index)throw new IOException("synthetic store failure");}
  public boolean clearPreferences()throws Exception{step("clear-preferences",1);return committed;}
  public boolean preferencesEmpty()throws Exception{step("verify-preferences",2);return empty;}
  public void deleteAlias()throws Exception{step("delete-alias",3);}
  public boolean aliasAbsent()throws Exception{step("verify-alias",4);return absent;}
 }
 private static void cancelledTransport(boolean cancelOnConnection)throws Exception{DeepSeekTransport transport=new DeepSeekTransport();FakeConnection[] connection={null};URL url=new URL(null,"https://api.deepseek.com/chat/completions",new URLStreamHandler(){protected URLConnection openConnection(URL u){FakeConnection c=new FakeConnection(u);connection[0]=c;if(cancelOnConnection)transport.cancel();else c.beforeOutput=()->transport.cancel();return c;}});boolean rejected=false;try{transport.sendTo(url,"synthetic-key-not-secret","synthetic-payload");}catch(IOException expected){rejected=true;}check(rejected);check(connection[0].output.size()==0);check(connection[0].responses==0);check(connection[0].disconnected);}
 public static void main(String[] args)throws Exception{
  if(args.length>0&&"--text-payload-fixtures".equals(args[0])){String text="  合成午餐 12.30 元\n\"quoted\" \\ end\t  ";for(String mode:new String[]{"budget","food"}){AiRequestContract typed=new AiRequestContract(1,mode,mode+"_text",19,"do-not-send-correlation",text);System.out.println(AiPayloadBuilder.text(typed,text));}return;}
  if(args.length>0&&"--payload-fixtures".equals(args[0])){for(String[] pair:new String[][]{{"budget","statement_image"},{"food","food_image"},{"food","food_camera"}})System.out.println(AiPayloadBuilder.image(new AiRequestContract(1,pair[0],pair[1],17,"do-not-send-correlation"),new byte[]{0,1,2,3,(byte)255},"image/png"));return;}
  for(String[] pair:new String[][]{{"budget","statement_image"},{"food","food_image"},{"food","food_camera"}}){AiRequestContract r=new AiRequestContract(1,pair[0],pair[1],7);check(r.mode.equals(pair[0]));check(r.source.equals(pair[1]));check(r.revision==7);}
  rejects(()->new AiRequestContract(2,"budget","statement_image",0));rejects(()->new AiRequestContract(1,"budget","statement_image",-1));rejects(()->new AiRequestContract(1,"food","statement_image",0));rejects(()->new AiRequestContract(1,"budget","food_camera",0));rejects(()->new AiRequestContract(1,"budget","execute_tool",0));rejects(()->new AiRequestContract(1,null,null,0));
  Set<String> fields=new HashSet<>(Arrays.asList("version","mode","source","revision","clientAttempt"));AiRequestContract.assertFields(fields);check(true);
  for(String forbidden:new String[]{"history","profile","weights","apiKey","endpoint","requestId","generation","tools"}){Set<String> extra=new HashSet<>(fields);extra.add(forbidden);rejects(()->AiRequestContract.assertFields(extra));}
  Set<String> missing=new HashSet<>(fields);missing.remove("revision");rejects(()->AiRequestContract.assertFields(missing));
  AiRequestContract.requireRequestSize(repeat("a",16384));check(true);rejects(()->AiRequestContract.requireRequestSize(repeat("a",16385)));rejects(()->AiRequestContract.requireRequestSize(repeat("界",5462)));rejects(()->AiRequestContract.requireRequestSize(null));
  AiRequestContract request=new AiRequestContract(1,"budget","statement_image",3);AiRequestSession session=new AiRequestSession();
  check(!session.busy());check(!session.isCurrent(null));rejects(()->session.reserve(null));
  AiRequestSession.Ticket first=session.reserve(request);check(first!=null);check(session.busy());check(session.isCurrent(first));check(first.request==request);check(first.generation==1);check(first.id.matches("[A-Za-z0-9-]{1,80}"));check(session.reserve(request)==null);
  AiRequestSession.Ticket foreign=new AiRequestSession().reserve(request);check(!session.release(foreign));check(session.isCurrent(first));check(!session.release(null));check(session.release(first));check(!session.release(first));check(!session.busy());
  AiRequestSession.Ticket next=session.reserve(request);check(next!=null);check(!next.id.equals(first.id));check(next.generation>first.generation);check(!session.release(first));check(session.isCurrent(next));
  check(next.sessionId.equals(first.sessionId));check(!next.sessionId.equals(foreign.sessionId));check(session.isCurrent(next.sessionId,next.id,next.generation,"budget","statement_image",3));check(!session.isCurrent("foreign",next.id,next.generation,"budget","statement_image",3));check(!session.isCurrent(next.sessionId,"foreign",next.generation,"budget","statement_image",3));check(!session.isCurrent(next.sessionId,next.id,next.generation+1,"budget","statement_image",3));check(!session.isCurrent(next.sessionId,next.id,next.generation,"food","statement_image",3));check(!session.isCurrent(next.sessionId,next.id,next.generation,"budget","food_image",3));check(!session.isCurrent(next.sessionId,next.id,next.generation,"budget","statement_image",4));
  AiRequestContract correlated=new AiRequestContract(1,"budget","statement_image",0,"local-attempt");check(correlated.clientAttempt.equals("local-attempt"));rejects(()->new AiRequestContract(1,"budget","statement_image",0,null));rejects(()->new AiRequestContract(1,"budget","statement_image",0,""));rejects(()->new AiRequestContract(1,"budget","statement_image",0,"../escape"));rejects(()->new AiRequestContract(1,"budget","statement_image",0,repeat("x",81)));
  AiRequestSession concurrent=new AiRequestSession();CountDownLatch ready=new CountDownLatch(16),start=new CountDownLatch(1);AtomicInteger winners=new AtomicInteger();List<Thread> threads=new ArrayList<>();
  for(int i=0;i<16;i++){Thread thread=new Thread(()->{ready.countDown();try{start.await();if(concurrent.reserve(request)!=null)winners.incrementAndGet();}catch(InterruptedException e){Thread.currentThread().interrupt();}});threads.add(thread);thread.start();}
  ready.await();start.countDown();for(Thread thread:threads)thread.join();check(winners.get()==1);check(concurrent.busy());
  byte[] image={1,2,3,4};AiConsentSnapshot snapshot=new AiConsentSnapshot(next,image,"image/png",approved->Base64.getEncoder().encodeToString(approved));
  check(snapshot.matches(next));check(!snapshot.matches(first));check(!snapshot.matches(null));check(snapshot.mime().equals("image/png"));check(snapshot.payload().equals("AQIDBA=="));image[0]=99;check(snapshot.copyImageBytes()[0]==1);byte[] returned=snapshot.copyImageBytes();returned[1]=99;check(snapshot.copyImageBytes()[1]==2);check(snapshot.payload().equals("AQIDBA=="));
  rejectsChecked(()->new AiConsentSnapshot(null,new byte[]{1},"image/png",b->"x"));rejectsChecked(()->new AiConsentSnapshot(next,null,"image/png",b->"x"));rejectsChecked(()->new AiConsentSnapshot(next,new byte[0],"image/png",b->"x"));rejectsChecked(()->new AiConsentSnapshot(next,new byte[10_000_000],"image/png",b->"x"));rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"text/html",b->"x"));rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"image/png",null));
  rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"image/png",b->{b[0]=2;return "changed";}));rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"image/png",b->null));rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"image/png",b->""));rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"image/png",b->repeat("a",15*1024*1024+1)));rejectsChecked(()->new AiConsentSnapshot(next,new byte[]{1},"image/png",b->repeat("界",5*1024*1024+1)));
  AiRequestSession cancelSession=new AiRequestSession();AiRequestSession.Ticket cancelTicket=cancelSession.reserve(request);AtomicInteger disconnects=new AtomicInteger(),deliveries=new AtomicInteger();AiRequestSession.Ticket[] replacement={null};
  Runnable queuedResponse=()->{if(cancelSession.release(cancelTicket))deliveries.incrementAndGet();};
  check(cancelSession.cancel(cancelTicket,()->{check(!cancelSession.isCurrent(cancelTicket));check(!cancelSession.busy());replacement[0]=cancelSession.reserve(request);disconnects.incrementAndGet();}));check(disconnects.get()==1);check(cancelSession.isCurrent(replacement[0]));queuedResponse.run();check(deliveries.get()==0);check(!cancelSession.cancel(cancelTicket,()->disconnects.incrementAndGet()));check(disconnects.get()==1);check(cancelSession.isCurrent(replacement[0]));check(cancelSession.cancel(replacement[0],null));check(!cancelSession.busy());
  cancelledTransport(true);cancelledTransport(false);
  AiRequestSession lifecycle=new AiRequestSession();AiRequestSession.Ticket beforeReset=lifecycle.reserve(request);check(lifecycle.isAlive());check(lifecycle.reset()==beforeReset);check(!lifecycle.isCurrent(beforeReset));check(!lifecycle.release(beforeReset));check(!lifecycle.busy());AiRequestSession.Ticket afterReset=lifecycle.reserve(request);check(!afterReset.sessionId.equals(beforeReset.sessionId));check(afterReset.generation>beforeReset.generation);check(!lifecycle.isCurrent(beforeReset.sessionId,beforeReset.id,beforeReset.generation,"budget","statement_image",3));check(lifecycle.close()==afterReset);check(!lifecycle.isAlive());check(!lifecycle.isCurrent(afterReset));check(lifecycle.reserve(request)==null);check(lifecycle.reset()==null);check(lifecycle.reserve(request)==null);check(!lifecycle.isAlive());check(!lifecycle.cancel(afterReset,()->{throw new AssertionError("Disposed transport invoked");}));
  rejects(()->AiPayloadBuilder.image(null,new byte[]{1},"image/png"));rejects(()->AiPayloadBuilder.image(request,null,"image/png"));rejects(()->AiPayloadBuilder.image(request,new byte[0],"image/png"));rejects(()->AiPayloadBuilder.image(request,new byte[10_000_000],"image/png"));rejects(()->AiPayloadBuilder.image(request,new byte[]{1},"text/html"));rejects(()->AiPayloadBuilder.image(request,new byte[]{1},"image/png\"}evil"));
  check(AiPayloadBuilder.quote("a\"\\\n\t").equals("\"a\\\"\\\\\\u000a\\u0009\""));check(AiPayloadBuilder.quote("合成测试").equals("\"合成测试\""));
  String json="{\"text\":\"quote\\\" slash\\\\ line\\n\",\"items\":[null,true,false,0,-0.5,1.25e2],\"emoji\":\"\\ud83d\\ude00\"}";Object parsed=AiJson.parse(json);check(AiJson.parse(AiJson.stringify(parsed)).equals(parsed));check(AiJson.parse("\"界\"",5).equals("界"));rejects(()->AiJson.parse("\"界\"",4));rejects(()->AiJson.parse("{}",0));
  for(String invalid:new String[]{"","{","[","01","-01","+1",".5","1.","1e","NaN","Infinity","1e309","[1,]","{\"a\":1,}","[true false]","true false","\u00a0{}","\"raw\nline\"","\"\\uD800\"","\"\\uDC00\"","\"\\uD800a\"","\"\\uZZZZ\"","{\"a\":1,\"a\":2}","{\"a\":1,\"\\u0061\":2}"})rejects(()->AiJson.parse(invalid));
  check(AiJson.parse(repeat("[",16)+"0"+repeat("]",16))!=null);rejects(()->AiJson.parse(repeat("[",17)+"0"+repeat("]",17)));rejects(()->AiJson.parse("["+repeat("0,",4095)+"0]"));
  rejects(()->AiJson.stringify(Double.NaN));rejects(()->AiJson.stringify(Double.POSITIVE_INFINITY));rejects(()->AiJson.stringify("\uD800"));rejects(()->AiJson.stringify(new Object()));List<Object> cycle=new ArrayList<>();cycle.add(cycle);rejects(()->AiJson.stringify(cycle));
  Map<String,Object> row=map("date","10-08","rawDate","10-08","type","expense","category","meals","amount","12.34","note","<script>synthetic</script>","source","");Map<String,Object> budgetDraft=map("records",Arrays.asList(row));String clean=AiResponseParser.parse(completion(budgetDraft),"budget");Map<String,Object> canonicalRow=new LinkedHashMap<>(row);canonicalRow.put("currency","");canonicalRow.put("rawAmount","12.34");check(AiJson.parse(clean).equals(map("records",Arrays.asList(canonicalRow))));check(AiJson.parse(AiResponseParser.parse(completion(map("records",Arrays.asList(map("note","missing fields remain unresolved")))),"budget"))!=null);
  rejects(()->AiResponseParser.parse(completion(budgetDraft),"execute"));rejects(()->AiResponseParser.parse(completion(map("records",new ArrayList<Object>())),"budget"));rejects(()->AiResponseParser.parse(completion(map("records",Arrays.asList(map()))),"budget"));List<Object> manyRows=new ArrayList<>();for(int i=0;i<101;i++)manyRows.add(row);rejects(()->AiResponseParser.parse(completion(map("records",manyRows)),"budget"));
  for(Map<String,Object> badRow:Arrays.asList(map("amount",12.34),map("note",repeat("x",201)),map("profile",map("weightKg",70)),map("url","https://example.invalid")))rejects(()->AiResponseParser.parse(completion(map("records",Arrays.asList(badRow))),"budget"));
  for(Map<String,Object> message:Arrays.asList(map("role","user","content",AiJson.stringify(budgetDraft)),map("content",AiJson.stringify(budgetDraft)),map("role","assistant","content",AiJson.stringify(budgetDraft),"tool_calls",Arrays.asList(map())),map("role","assistant","content",AiJson.stringify(budgetDraft),"refusal","no"),map("role","assistant","content",AiJson.stringify(budgetDraft),"reasoning_content","unexpected reasoning"),map("role","assistant","content","```json\n{}\n```")))rejects(()->AiResponseParser.parse(AiJson.stringify(map("choices",Arrays.asList(map("finish_reason","stop","message",message)))),"budget"));
  Map<String,Object> truncatedChoice=map("finish_reason","length","message",map("role","assistant","content",AiJson.stringify(budgetDraft)));rejects(()->AiResponseParser.parse(AiJson.stringify(map("choices",Arrays.asList(truncatedChoice))),"budget"));
  Map<String,Object> food=map("name","合成食物","portionGrams",100,"caloriesLow",0,"caloriesHigh",200,"confidence","low","note","");check(AiResponseParser.parse(completion(food),"food").contains("合成食物"));for(String field:new String[]{"profile","exercise","deficit","tools"}){Map<String,Object> badFood=new LinkedHashMap<>(food);badFood.put(field,map());rejects(()->AiResponseParser.parse(completion(badFood),"food"));}for(Object[] patch:new Object[][]{{"name",""},{"portionGrams",0},{"portionGrams",-1},{"caloriesLow",201},{"confidence",.95},{"confidence","certain"},{"caloriesHigh",1000001}}){Map<String,Object> badFood=new LinkedHashMap<>(food);badFood.put((String)patch[0],patch[1]);rejects(()->AiResponseParser.parse(completion(badFood),"food"));}
  FakeKeyStore goodStore=new FakeKeyStore();AiKeyDeletion.Result deletion=AiKeyDeletion.clear(goodStore,()->goodStore.events.add("invalidate"));check(deletion.success);check(deletion.preferencesCleared);check(deletion.aliasCleared);check(goodStore.events.equals(Arrays.asList("invalidate","clear-preferences","verify-preferences","delete-alias","verify-alias")));
  for(int failure=1;failure<=4;failure++){FakeKeyStore store=new FakeKeyStore();store.fail=failure;AiKeyDeletion.Result failureResult=AiKeyDeletion.clear(store,()->store.events.add("invalidate"));check(!failureResult.success);check(store.events.contains("delete-alias"));check(failureResult.preferencesCleared==(failure>=3));check(failureResult.aliasCleared==(failure<=2));}
  for(int failure=0;failure<3;failure++){FakeKeyStore store=new FakeKeyStore();if(failure==0)store.committed=false;if(failure==1)store.empty=false;if(failure==2)store.absent=false;AiKeyDeletion.Result failureResult=AiKeyDeletion.clear(store,()->store.events.add("invalidate"));check(!failureResult.success);check(store.events.contains("delete-alias"));}
  rejects(()->AiKeyDeletion.clear(null,()->{}));rejects(()->AiKeyDeletion.clear(goodStore,null));
  for(Object[] statusCase:new Object[][]{{401,"auth"},{403,"auth"},{402,"balance"},{429,"rate"},{302,"server"},{500,"server"}}){FakeConnection[] conn={null};URL u=new URL(null,"https://api.deepseek.com/chat/completions",new URLStreamHandler(){protected URLConnection openConnection(URL value){FakeConnection c=new FakeConnection(value);c.status=(Integer)statusCase[0];conn[0]=c;return c;}});boolean failed=false;try{new DeepSeekTransport().sendTo(u,"synthetic-key","synthetic-body");}catch(DeepSeekTransport.Failure failure){failed=true;check(failure.code.equals(statusCase[1]));}check(failed);check(conn[0].responses==1);check(conn[0].inputReads==0);check(!conn[0].getInstanceFollowRedirects());check(conn[0].disconnected);}
  for(String code:new String[]{"auth","balance","rate","timeout","input","parse","cancelled","network","server","unknown"}){AiErrors.Info info=AiErrors.forCode(code);check(!info.message.isEmpty());check(Arrays.asList("configure","account","wait","reselect","edit","none").contains(info.action));check(!info.message.contains("SECRET-MARKER"));check(info.code.equals(code.equals("unknown")?"server":code));}
  for(Throwable failure:new Throwable[]{new SocketTimeoutException("SECRET-MARKER"),new IOException("SECRET-MARKER"),new IllegalArgumentException("SECRET-MARKER"),new RuntimeException("SECRET-MARKER"),new DeepSeekTransport.Failure("auth","SECRET-MARKER")}){AiErrors.Info info=AiErrors.from(failure);check(!info.message.contains("SECRET-MARKER"));check(!info.action.contains("SECRET-MARKER"));}check(AiErrors.from(new SocketTimeoutException()).code.equals("timeout"));check(AiErrors.from(new IOException()).code.equals("network"));check(AiErrors.from(new IllegalArgumentException()).code.equals("parse"));
  for(int orientation=1;orientation<=8;orientation++){AiImagePolicy.Plan p=AiImagePolicy.plan(1200,800,false,orientation,64L*1024*1024);check(p.sampleSize==1);check(p.outputWidth==(orientation>=5?800:1200));check(p.outputHeight==(orientation>=5?1200:800));check(p.estimatedBytes==1200L*800*4*(orientation==1?1:2));check(AiImagePolicy.swapsAxes(orientation)==(orientation>=5));}
  for(int[] dims:new int[][]{{0,1},{1,0},{-1,100},{65536,1},{1,65536},{Integer.MAX_VALUE,Integer.MAX_VALUE}}){rejects(()->AiImagePolicy.plan(dims[0],dims[1],true,1,1024));rejects(()->AiImagePolicy.previewSample(dims[0],dims[1]));}
  for(int orientation:new int[]{-1,0,9,Integer.MAX_VALUE}){rejects(()->AiImagePolicy.plan(1,1,true,orientation,1024));rejects(()->AiImagePolicy.swapsAxes(orientation));}
  rejects(()->AiImagePolicy.plan(1,1,false,1,7));rejects(()->AiImagePolicy.plan(1,1,false,1,AiImagePolicy.MAX_BITMAP_BUDGET+1));check(AiImagePolicy.plan(8192,8192,false,1,AiImagePolicy.MAX_BITMAP_BUDGET).sampleSize==2);
  AiImagePolicy.Plan exact=AiImagePolicy.plan(4096,4096,false,1,AiImagePolicy.MAX_BITMAP_BUDGET);check(exact.sampleSize==1);check(exact.estimatedBytes==AiImagePolicy.MAX_BITMAP_BUDGET);check(AiImagePolicy.plan(4096,4096,false,2,AiImagePolicy.MAX_BITMAP_BUDGET).sampleSize==2);
  for(int[] dims:new int[][]{{8192,8192},{8192,1},{1,8192},{4097,2049},{1,1}})for(int orientation=1;orientation<=8;orientation++){AiImagePolicy.Plan p=AiImagePolicy.plan(dims[0],dims[1],true,orientation,1024*1024);check(p.sampleSize>0&&(p.sampleSize&(p.sampleSize-1))==0);check(p.outputWidth>0&&p.outputWidth<=2048);check(p.outputHeight>0&&p.outputHeight<=2048);check(p.estimatedBytes<=1024*1024);int sample=AiImagePolicy.previewSample(dims[0],dims[1]);check((sample&(sample-1))==0);check((dims[0]+sample-1)/sample<=1024);check((dims[1]+sample-1)/sample<=1024);}
  AiImagePolicy.Plan tiny=AiImagePolicy.plan(8192,8192,true,8,8);check(tiny.sampleSize==8192);check(tiny.outputWidth==1&&tiny.outputHeight==1);check(tiny.estimatedBytes==8);check(AiImagePolicy.previewSample(1024,1)==1);check(AiImagePolicy.previewSample(1025,1)==2);
  rejects(()->new AiBoundedBytes(0));rejects(()->new AiBoundedBytes(-1));rejects(()->new AiBoundedBytes(AiBoundedBytes.MAX_BYTES+1));
  AiBoundedBytes bounded=new AiBoundedBytes(4);bounded.write(255);bounded.write(new byte[]{9,2,3,9},1,2);check(Arrays.equals(bounded.toByteArray(),new byte[]{-1,2,3}));byte[] copy=bounded.toByteArray();copy[0]=0;check(bounded.toByteArray()[0]==-1);boolean overflow=false;try{bounded.write(new byte[]{4,5},0,2);}catch(IOException expected){overflow=true;}check(overflow);check(bounded.size()==3);bounded.write(4);check(bounded.size()==4);overflow=false;try{bounded.write(5);}catch(IOException expected){overflow=true;}check(overflow);check(Arrays.equals(bounded.toByteArray(),new byte[]{-1,2,3,4}));bounded.write(new byte[0],0,0);check(bounded.size()==4);
  for(int[] range:new int[][]{{-1,1},{0,-1},{2,1},{Integer.MAX_VALUE,1},{0,Integer.MAX_VALUE}}){boolean rejected=false;try{bounded.write(new byte[]{1},range[0],range[1]);}catch(IndexOutOfBoundsException expected){rejected=true;}check(rejected);check(bounded.size()==4);}
  boolean nullRejected=false;try{bounded.write(null,0,0);}catch(NullPointerException expected){nullRejected=true;}check(nullRejected);AiBoundedBytes fullImage=new AiBoundedBytes(AiBoundedBytes.MAX_BYTES);fullImage.write(new byte[AiBoundedBytes.MAX_BYTES]);check(fullImage.size()==AiBoundedBytes.MAX_BYTES);overflow=false;try{fullImage.write(1);}catch(IOException expected){overflow=true;}check(overflow);
  for(String mode:new String[]{"budget","food"}){AiRequestContract req=new AiRequestContract(1,mode,mode.equals("budget")?"statement_image":"food_image",1,"private-correlation");String disclosure=AiDisclosure.image(req,1200,800,12345);check(disclosure.contains(DeepSeekTransport.ENDPOINT));check(disclosure.contains(AiPayloadBuilder.MODEL));check(disclosure.contains("1200 × 800"));check(disclosure.contains("12345 字节"));check(disclosure.contains(mode.equals("food")?"JPEG":"PNG"));check(disclosure.contains("可能收费"));check(disclosure.contains("不会自动重试"));check(disclosure.contains("取消不会发送"));check(disclosure.contains("体重或身体资料"));check(!disclosure.contains("private-correlation"));check(AiPayloadBuilder.instruction(req).length()>0);}
  rejects(()->AiDisclosure.image(null,1,1,1));for(int[] bad:new int[][]{{0,1,1},{1,0,1},{8193,1,1},{1,8193,1},{1,1,0},{1,1,AiBoundedBytes.MAX_BYTES+1}})rejects(()->AiDisclosure.image(request,bad[0],bad[1],bad[2]));
  check(!AiDisclosure.maySend(false,false));check(!AiDisclosure.maySend(false,true));check(!AiDisclosure.maySend(true,false));check(AiDisclosure.maySend(true,true));String privacy=AiDisclosure.image(request,1,1,1);for(String required:new String[]{"必须", "完整卡号", "银行账号", "密码", "验证码", "API 密钥", "不会自动遮盖"})check(privacy.contains(required));
  AiConsentSelection slot=new AiConsentSelection();AiConsentSnapshot replacementSnapshot=new AiConsentSnapshot(next,new byte[]{5},"image/png",b->"replacement");check(!slot.isCurrent(next,snapshot));rejects(()->slot.replace(null,snapshot));rejects(()->slot.replace(next,null));rejects(()->slot.replace(first,snapshot));slot.replace(next,snapshot);check(slot.isCurrent(next,snapshot));check(!slot.isCurrent(first,snapshot));check(!slot.invalidate(first));check(slot.isCurrent(next,snapshot));slot.replace(next,replacementSnapshot);check(!slot.consume(next,snapshot));check(slot.isCurrent(next,replacementSnapshot));check(slot.consume(next,replacementSnapshot));check(!slot.consume(next,replacementSnapshot));slot.replace(next,snapshot);check(slot.invalidate(next));check(!slot.isCurrent(next,snapshot));check(!slot.invalidate(next));slot.replace(next,snapshot);slot.reset();check(!slot.consume(next,snapshot));
  slot.replace(next,snapshot);AtomicInteger sendWinners=new AtomicInteger();List<Thread> consentThreads=new ArrayList<>();for(int n=0;n<16;n++){Thread t=new Thread(()->{if(slot.consume(next,snapshot))sendWinners.incrementAndGet();});consentThreads.add(t);t.start();}for(Thread t:consentThreads)t.join();check(sendWinners.get()==1);
  rejects(()->AiCaptureCleanup.clean(null));for(int scenario=0;scenario<6;scenario++){final int failure=scenario;List<String> events=new ArrayList<>();AiCaptureCleanup.Result result=AiCaptureCleanup.clean(new AiCaptureCleanup.Resources(){public void revokeGrant()throws Exception{events.add("revoke");if(failure==1)throw new IOException();}public boolean deleteTemporaryFile()throws Exception{events.add("delete");if(failure==2)throw new IOException();return failure!=3;}public boolean temporaryFileAbsent()throws Exception{events.add("verify");if(failure==4)throw new IOException();return failure!=5;}});check(events.get(0).equals("revoke"));check(events.contains("delete"));check(result.grantRevoked==(failure!=1));check(result.fileRemoved==(failure==0||failure==1));check(result.success==(failure==0));}
  String exactText="  合成午餐 12.30 元\n\"quoted\" \\ end  ";for(String mode:new String[]{"budget","food"}){AiRequestContract typed=new AiRequestContract(1,mode,mode+"_text",7,"typed-correlation",exactText);check(typed.text.equals(exactText));Map<?,?> payload=(Map<?,?>)AiJson.parse(AiPayloadBuilder.text(typed,exactText));List<?> messages=(List<?>)payload.get("messages");check(messages.size()==2);check(((Map<?,?>)messages.get(0)).get("role").equals("system"));check(((Map<?,?>)messages.get(1)).get("role").equals("user"));check(((Map<?,?>)messages.get(1)).get("content").equals(exactText));check(!AiPayloadBuilder.text(typed,exactText).contains("typed-correlation"));AiRequestSession.Ticket typedTicket=new AiRequestSession().reserve(typed);AiConsentSnapshot typedSnapshot=new AiConsentSnapshot(typedTicket,exactText,t->AiPayloadBuilder.text(typed,t));check(typedSnapshot.isText());check(typedSnapshot.text().equals(exactText));check(typedSnapshot.mime().equals("text/plain"));rejects(()->AiPayloadBuilder.text(typed,exactText.trim()));rejectsChecked(()->new AiConsentSnapshot(typedTicket,exactText.trim(),t->"x"));}
  for(String invalid:new String[]{null,"","  ",repeat("a",4001),"\uD800","\uDC00"})rejects(()->AiRequestContract.validateText(invalid));check(AiRequestContract.validateText(repeat("界",4000)).length()==4000);rejects(()->new AiRequestContract(1,"food","food_image",0,"attempt","extra context"));rejects(()->new AiRequestContract(1,"budget","budget_text",0,"attempt",null));
  AiRequestSession attemptSession=new AiRequestSession();check(!attemptSession.ownsAttempt("target"));AiRequestSession.Ticket attemptTicket=attemptSession.reserve(new AiRequestContract(1,"budget","budget_text",0,"target","synthetic"));check(attemptSession.ownsAttempt("target"));check(!attemptSession.ownsAttempt("other"));check(!attemptSession.ownsAttempt(null));attemptSession.release(attemptTicket);check(!attemptSession.ownsAttempt("target"));
  AiRequestSession retrySession=new AiRequestSession();AiRequestSession.Ticket failedTicket=retrySession.reserve(new AiRequestContract(1,"budget","budget_text",4,"failed-attempt"," exact retry "));AiConsentSnapshot failedSnapshot=new AiConsentSnapshot(failedTicket," exact retry ",t->"frozen-payload");AiRetryStore retries=new AiRetryStore();retries.offer(failedTicket,failedSnapshot);check(retries.availableFor(failedTicket.id));check(!retries.availableFor("wrong"));retrySession.release(failedTicket);
  for(int bad=0;bad<5;bad++){final int b=bad;AiRequestContract retryRequest=new AiRequestContract(1,"budget","budget_text",b==1?5:4,b==2?"failed-attempt":"new-attempt",b==3?"different":" exact retry ",b==0?"wrong":failedTicket.id);AiRequestSession owner=b==4?new AiRequestSession():retrySession;AiRequestSession.Ticket replacementTicket=owner.reserve(retryRequest);rejectsChecked(()->retries.take(replacementTicket));owner.release(replacementTicket);check(retries.availableFor(failedTicket.id));}
  AiRequestSession.Ticket retryTicket=retrySession.reserve(new AiRequestContract(1,"budget","budget_text",4,"new-attempt"," exact retry ",failedTicket.id));AiConsentSnapshot rebound=retries.take(retryTicket);check(rebound.matches(retryTicket));check(rebound.payload().equals(failedSnapshot.payload()));check(rebound.text().equals(failedSnapshot.text()));check(!retries.availableFor(failedTicket.id));rejectsChecked(()->retries.take(retryTicket));retries.offer(failedTicket,failedSnapshot);retries.clear();check(!retries.availableFor(failedTicket.id));
  Map<?,?> partialFood=(Map<?,?>)AiJson.parse(AiResponseParser.parse(completion(map("name","synthetic meal","caloriesLow",0)),"food"));check(partialFood.get("portionGrams")==null);check(((Number)partialFood.get("caloriesLow")).doubleValue()==0);check(partialFood.get("caloriesHigh")==null);Map<?,?> nullFood=(Map<?,?>)AiJson.parse(AiResponseParser.parse(completion(map("name","synthetic meal","portionGrams",null,"caloriesLow",null,"caloriesHigh",12)),"food"));check(nullFood.get("caloriesLow")==null);check(((Number)nullFood.get("caloriesHigh")).doubleValue()==12);
  for(String reason:new String[]{"nonfood","unreadable","insufficient"})check(AiJson.parse(AiResponseParser.parse(completion(map("outcome","unrecognized","reason",reason)),"food")).equals(map("outcome","unrecognized","reason",reason)));rejects(()->AiResponseParser.parse(completion(map("outcome","unrecognized","reason","execute")),"food"));rejects(()->AiResponseParser.parse(completion(map("outcome","unrecognized","reason","nonfood","name","invented")),"food"));
  for(String control:new String[]{"spoof\u202Etext","spoof\u2066text","control\u0001text"}){rejects(()->AiResponseParser.parse(completion(map("records",Arrays.asList(map("note",control)))),"budget"));rejects(()->AiResponseParser.parse(completion(map("name",control)),"food"));}
  AiDeliveryGate gate=new AiDeliveryGate();AiDeliveryGate.Owner deliveryOwner=gate.begin("request-one");String startedToken=gate.issue(deliveryOwner,"started"),phaseToken=gate.issue(deliveryOwner,"phase"),resultToken=gate.issue(deliveryOwner,"result");check(gate.issue(deliveryOwner,"phase")==null);gate.finish(deliveryOwner);check(gate.consume(startedToken,"request-one","started"));check(!gate.consume(startedToken,"request-one","started"));check(!gate.consume(phaseToken,"wrong","phase"));check(gate.consume(phaseToken,"request-one","phase"));check(gate.consume(resultToken,"request-one","result"));
  AiDeliveryGate.Owner staleOwner=gate.begin("stale-request");String queued=gate.issue(staleOwner,"result");gate.invalidate();check(!gate.consume(queued,"stale-request","result"));check(gate.issue(staleOwner,"result")==null);AiDeliveryGate.Owner freshOwner=gate.begin("fresh-request");String freshToken=gate.issue(freshOwner,"started");gate.revokeRequest("stale-request");check(gate.consume(freshToken,"fresh-request","started"));gate.revokeRequest("fresh-request");check(gate.issue(freshOwner,"result")==null);String cancelledToken=gate.cancellation("fresh-request");check(!gate.consume(cancelledToken,"fresh-request","result"));check(gate.consume(cancelledToken,"fresh-request","cancelled"));gate.close();check(gate.cancellation("fresh-request")==null);check(gate.issue(freshOwner,"error")==null);
  AiDeliveryGate boundedGate=new AiDeliveryGate();AiDeliveryGate.Owner boundedOwner=boundedGate.begin("bounded");for(int n=0;n<AiDeliveryGate.MAX_PENDING;n++)check(boundedGate.issue(boundedOwner,"phase")!=null);check(boundedGate.issue(boundedOwner,"phase")==null);boundedGate.invalidate();check(boundedGate.issue(boundedOwner,"result")==null);
  AiSourceRegistry registry=new AiSourceRegistry();AiSourceRegistry.Launch launch=registry.reserve(next,"food_camera");check(registry.take(launch.code)==launch);check(registry.take(launch.code)==null);AiSourceRegistry.Launch staleLaunch=registry.reserve(next,"food_image");registry.reset();AiSourceRegistry.Launch freshLaunch=registry.reserve(first,"food_image");check(freshLaunch.code>staleLaunch.code);check(registry.take(staleLaunch.code)==null);registry.revoke(next);check(registry.take(freshLaunch.code)==freshLaunch);int floor=AiSourceRegistry.floor();AiSourceRegistry.advanceTo(floor+10);AiSourceRegistry.advanceTo(floor);check(AiSourceRegistry.floor()==floor+10);AiSourceRegistry otherRegistry=new AiSourceRegistry();check(otherRegistry.reserve(next,"statement_image").code>=floor+10);rejects(()->AiSourceRegistry.advanceTo(0));rejects(()->registry.reserve(null,"food_image"));rejects(()->registry.reserve(next,"execute"));int rejectedCode=AiSourceRegistry.floor();boolean persistFailed=false;try{registry.reserve(next,"food_image",value->false);}catch(IllegalStateException expected){persistFailed=true;}check(persistFailed);check(registry.take(rejectedCode)==null);check(AiSourceRegistry.floor()>rejectedCode);AtomicInteger persistedFloor=new AtomicInteger();AiSourceRegistry.Launch durable=registry.reserve(next,"food_image",value->{persistedFloor.set(value);return true;});check(persistedFloor.get()==durable.code+1);check(registry.take(durable.code)==durable);AiSourceRegistry.advanceTo(AiSourceRegistry.LAST+1);boolean exhausted=false;try{registry.reserve(next,"food_image");}catch(IllegalStateException expected){exhausted=true;}check(exhausted);
  List<String> captureNames=new ArrayList<>();for(int n=0;n<AiCapturePath.MAX_ACTIVE;n++){String name=AiCapturePath.acquire();check(AiCapturePath.isFileName(name));check(AiCapturePath.isActive(name));check(AiCapturePath.fileName(AiCapturePath.path(name)).equals(name));check(!captureNames.contains(name));captureNames.add(name);}boolean captureFull=false;try{AiCapturePath.acquire();}catch(IllegalStateException expected){captureFull=true;}check(captureFull);AiCapturePath.release("unrelated");check(AiCapturePath.isActive(captureNames.get(0)));for(String name:captureNames){AiCapturePath.release(name);check(!AiCapturePath.isActive(name));}String unique=AiCapturePath.acquire();check(!captureNames.contains(unique));AiCapturePath.release(unique);check(!AiCapturePath.isFileName("../food-capture.jpg"));
  AiDeliveryGate receiptGate=new AiDeliveryGate();AiDeliveryGate.Owner receiptOwner=receiptGate.begin("receipt-request");String receiptToken=receiptGate.issue(receiptOwner,"result");check(!receiptGate.isResultCurrent(receiptToken,"receipt-request"));check(receiptGate.consume(receiptToken,"receipt-request","result"));receiptGate.finish(receiptOwner);check(receiptGate.isResultCurrent(receiptToken,"receipt-request"));check(!receiptGate.isResultCurrent(receiptToken,"other"));receiptGate.revokeRequest("receipt-request");check(!receiptGate.isResultCurrent(receiptToken,"receipt-request"));String oldest=null;for(int n=0;n<=AiDeliveryGate.MAX_RECEIPTS;n++){AiDeliveryGate.Owner owner=receiptGate.begin("receipt-"+n);String token=receiptGate.issue(owner,"result");if(n==0)oldest=token;check(receiptGate.consume(token,"receipt-"+n,"result"));receiptGate.finish(owner);}check(!receiptGate.isResultCurrent(oldest,"receipt-0"));receiptGate.invalidate();check(!receiptGate.isResultCurrent(oldest,"receipt-0"));
  System.out.println("PASS: "+assertions+" independent AI contract/session/snapshot/cancellation assertions; no network or real data.");
 }
}
