package cn.dot.budget;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.os.Build;
import android.security.keystore.*;
import android.text.InputType;
import android.util.Base64;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.security.KeyStore;
import javax.crypto.*;
import javax.crypto.spec.GCMParameterSpec;
import org.json.*;

final class StatementImport {
 private final Activity activity;
 private final java.util.function.Consumer<String> events;
 private final AiDeliveryGate deliveries=new AiDeliveryGate();
 private final AiSourceRegistry sources=new AiSourceRegistry();
 private final java.util.Map<AiRequestSession.Ticket,AiDeliveryGate.Owner> deliveryOwners=new java.util.IdentityHashMap<>();
 private final AiRequestSession requests=new AiRequestSession();
 private AiRequestSession.Ticket activeTicket;
 private final AiConsentSelection selection=new AiConsentSelection();
 private Runnable sourceLauncher;
 private final AiRetryStore retryStore=new AiRetryStore();
 private String sessionKey="";
 private boolean keyBlocked;
 private DeepSeekTransport transport;
 private int pageGeneration;
 private final java.util.Set<Dialog> dialogs=new java.util.HashSet<>();
 private static final String ALIAS="yueyouyu.deepseek.key.v1";
 StatementImport(Activity a,java.util.function.Consumer<String> events){activity=a;this.events=events;}
 void request(AiRequestContract request,java.util.function.IntConsumer camera){
  if(!requests.isAlive()||activity.isFinishing()||activity.isDestroyed())return;
  final AiRequestSession.Ticket ticket=requests.reserve(request);if(ticket==null){message("已有识别请求正在进行，请先完成或取消");return;}activeTicket=ticket;deliveryOwners.put(ticket,deliveries.begin(ticket.id));if(request.retryOf==null)retryStore.clear();emit(ticket,"started",null,null);
  Runnable start=()->{if(!requests.isCurrent(ticket))return;emit(ticket,"phase","preparing",null);try{if(request.retryOf!=null){AiConsentSnapshot frozen=retryStore.take(ticket);selection.replace(ticket,frozen);if(frozen.isText())confirmText(ticket,frozen);else confirmImage(ticket,frozen,"food".equals(request.mode));return;}if(request.text!=null){confirmText(ticket,null);return;}if("food_camera".equals(request.source)){AiSourceRegistry.Launch launch=reserveSource(ticket,request.source);camera.accept(launch.code);return;}Intent intent=new Intent(Intent.ACTION_GET_CONTENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);AiSourceRegistry.Launch launch=reserveSource(ticket,request.source);activity.startActivityForResult(intent,launch.code);}catch(Exception e){cancelSelection();message("本次图片来源暂不可用，请改用文字或手动填写；也可完全关闭应用后重试");}};
  sourceLauncher=start;if(loadKey().isEmpty())configure(start,()->finishSelection(ticket));else start.run();
 }
 private void emit(AiRequestSession.Ticket ticket,String event,String data,String error){emit(ticket,event,data,error,null);}
 private void emit(AiRequestSession.Ticket ticket,String event,String data,String error,String errorCode){try{AiRequestContract request=ticket.request;JSONObject value=new JSONObject().put("version",AiRequestContract.VERSION).put("event",event).put("mode",request.mode).put("source",request.source).put("requestId",ticket.id).put("sessionId",ticket.sessionId).put("generation",ticket.generation).put("revision",request.revision).put("clientAttempt",request.clientAttempt);String deliveryToken="cancelled".equals(event)?deliveries.cancellation(ticket.id):deliveries.issue(deliveryOwners.get(ticket),event);if(deliveryToken!=null)value.put("deliveryToken",deliveryToken);if(data!=null)value.put("phase".equals(event)?"phase":"data",data);if(error!=null)value.put("error",error).put("errorCode",errorCode).put("retryable",retryStore.availableFor(ticket.id));events.accept(value.toString());if("result".equals(event)||"error".equals(event)||"cancelled".equals(event)){deliveries.finish(deliveryOwners.remove(ticket));}}catch(JSONException ignored){}}
 private void finishSelection(AiRequestSession.Ticket ticket){if(requests.release(ticket)){sources.revoke(ticket);deliveries.revokeRequest(ticket.id);activeTicket=null;sourceLauncher=null;selection.invalidate(ticket);emit(ticket,"cancelled",null,null);}}
 void cancelSelection(){finishSelection(activeTicket);}
 private android.content.SharedPreferences prefs(){return activity.getSharedPreferences("deepseek-secure",0);}
 private javax.crypto.SecretKey storageKey()throws Exception{KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias(ALIAS)){KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return (javax.crypto.SecretKey)k.getKey(ALIAS,null);}
 private String loadKey(){if(keyBlocked)return "";if(!sessionKey.isEmpty())return sessionKey;String encoded=prefs().getString("encrypted",null);if(encoded==null)return "";try{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,storageKey(),new GCMParameterSpec(128,Base64.decode(prefs().getString("iv",""),Base64.NO_WRAP)));return new String(c.doFinal(Base64.decode(encoded,Base64.NO_WRAP)),java.nio.charset.StandardCharsets.UTF_8);}catch(Exception e){message("保存的密钥不可读取，请重新输入");return "";}}
 void configure(Runnable after){configure(after,null);}
 private void configure(Runnable after,Runnable cancelled){
  final boolean[] used={false};final int openedPage=pageGeneration;
  LinearLayout layout=new LinearLayout(activity);layout.setOrientation(1);layout.setPadding(40,12,40,12);
  TextView notice=new TextView(activity);notice.setText("直接连接 DeepSeek 官方 API（deepseek-flash）。API 可能产生费用，由你的 DeepSeek 账户承担。密钥只在手机输入，不放入账目备份。\n默认仅本次运行使用；勾选后通过 Android Keystore 加密保存在本机。");layout.addView(notice);
  EditText key=new EditText(activity);key.setHint("输入 DeepSeek API Key");key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setSingleLine();key.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);layout.addView(key);
  CheckBox remember=new CheckBox(activity);remember.setText("允许加密保存此密钥到本机");layout.addView(remember);
  AlertDialog d=new AlertDialog.Builder(activity).setTitle("配置 DeepSeek").setView(layout).setNegativeButton("取消",null).setPositiveButton("使用",null).create();d.getWindow();d.setOnShowListener(v->{d.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(w->{if(openedPage!=pageGeneration||!requests.isAlive()){d.dismiss();return;}String s=key.getText().toString().trim();if(s.length()<10||s.length()>512||s.contains("\n")||s.contains("\r")){key.setError("请输入有效密钥");return;}try{if(remember.isChecked()){Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,storageKey());if(!prefs().edit().putString("encrypted",Base64.encodeToString(c.doFinal(s.getBytes(java.nio.charset.StandardCharsets.UTF_8)),Base64.NO_WRAP)).putString("iv",Base64.encodeToString(c.getIV(),Base64.NO_WRAP)).commit())throw new IOException();}else if(!prefs().edit().clear().commit()||!prefs().getAll().isEmpty())throw new IOException();sessionKey=s;keyBlocked=false;used[0]=true;key.setText("");d.dismiss();if(after!=null)after.run();}catch(Exception e){message("密钥保存失败，未开始识别");}});});d.setOnDismissListener(v->{dialogs.remove(d);key.setText("");if(!used[0]&&cancelled!=null)cancelled.run();});showDialog(d);
 }
 void clear(){final int openedPage=pageGeneration;AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("清除 DeepSeek 密钥？").setMessage("清除本次运行和本机保存的密钥，并取消尚未完成的识别。不会删除账目或注销 DeepSeek 账户。已发送的请求仍可能产生费用。").setNegativeButton("取消",null).setPositiveButton("清除",(d,w)->{
  if(openedPage!=pageGeneration||!requests.isAlive())return;
  AiKeyDeletion.Result cleared=AiKeyDeletion.clear(new AiKeyDeletion.Store(){
   public boolean clearPreferences(){return prefs().edit().clear().commit();}
   public boolean preferencesEmpty(){return prefs().getAll().isEmpty();}
   private KeyStore keyStore()throws Exception{KeyStore keyStore=KeyStore.getInstance("AndroidKeyStore");keyStore.load(null);return keyStore;}
   public void deleteAlias()throws Exception{keyStore().deleteEntry(ALIAS);}
   public boolean aliasAbsent()throws Exception{return !keyStore().containsAlias(ALIAS);}
  },()->{sessionKey="";keyBlocked=true;cancelCurrent();});
  message(cleared.success?"本次运行和本机保存的密钥已确认清除":"本次运行已停用旧密钥，识别已停止；本机保存项未能确认全部删除。重新打开应用前请重试清除。");
 }).create();dialog.setOnDismissListener(d->dialogs.remove(dialog));showDialog(dialog);}
 boolean consumeDelivery(String token,String requestId,String event){return deliveries.consume(token,requestId,event);}
 boolean isResultCurrent(String token,String requestId){return deliveries.isResultCurrent(token,requestId);}
 void clearRetry(){retryStore.clear();}
 void cancelAttempt(String attempt){if(requests.ownsAttempt(attempt))cancelCurrent();}
 private void cancelCurrent(){deliveries.invalidate();deliveryOwners.clear();sources.reset();retryStore.clear();AiRequestSession.Ticket ticket=activeTicket;DeepSeekTransport old=transport;if(ticket!=null&&requests.cancel(ticket,old==null?null:old::cancel)){activeTicket=null;sourceLauncher=null;selection.invalidate(ticket);transport=null;emit(ticket,"cancelled",null,null);}for(Dialog dialog:new java.util.ArrayList<Dialog>(dialogs))dialog.dismiss();dialogs.clear();}

 void choose(){request(new AiRequestContract(1,"budget","statement_image",0),null);}
 void chooseFood(){request(new AiRequestContract(1,"food","food_image",0),null);}
 void prepareFoodCamera(java.util.function.IntConsumer start){request(new AiRequestContract(1,"food","food_camera",0),start);}
 private AiSourceRegistry.Launch reserveSource(AiRequestSession.Ticket ticket,String kind){return sources.reserve(ticket,kind,floor->{android.content.SharedPreferences store=activity.getSharedPreferences("ai-source-safety",0);return store.edit().putInt("next-code",floor).commit()&&store.getInt("next-code",0)>=floor;});}
 void sourceResult(int code,boolean success,Uri uri){AiSourceRegistry.Launch launch=sources.take(code);if(launch==null||!requests.isCurrent(launch.ticket))return;if(!success||uri==null){finishSelection(launch.ticket);return;}selected(launch.ticket,uri,!"statement_image".equals(launch.kind));}
 void selected(Uri uri){selected(uri,false);}
 void selectedFood(Uri uri){selected(uri,true);}
 private void confirmText(AiRequestSession.Ticket ticket,AiConsentSnapshot prepared){if(!requests.isCurrent(ticket))return;emit(ticket,"phase","consent",null);try{AiConsentSnapshot snapshot=prepared!=null?prepared:new AiConsentSnapshot(ticket,ticket.request.text,text->AiPayloadBuilder.text(ticket.request,text));selection.replace(ticket,snapshot);LinearLayout layout=new LinearLayout(activity);layout.setOrientation(1);layout.setPadding(32,12,32,12);TextView disclosure=new TextView(activity);disclosure.setText((ticket.request.retryOf!=null?"重新发送同一内容可能再次收费，请重新确认。\n":"")+AiDisclosure.text(ticket.request));layout.addView(disclosure);TextView exact=new TextView(activity);exact.setText(snapshot.text());exact.setTextIsSelectable(true);exact.setContentDescription("本次实际发送的完整文字");exact.setPadding(12,24,12,24);layout.addView(exact);Button reveal=new Button(activity);reveal.setText("查看固定识别说明");layout.addView(reveal);TextView prompt=new TextView(activity);prompt.setText(AiPayloadBuilder.instruction(ticket.request));prompt.setTextIsSelectable(true);prompt.setVisibility(View.GONE);layout.addView(prompt);reveal.setOnClickListener(v->prompt.setVisibility(prompt.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));CheckBox reviewed=new CheckBox(activity);reviewed.setText("我已核对以上完整文字，已移除完整卡号、账号、密码、验证码和 API 密钥");layout.addView(reviewed);ScrollView scroll=new ScrollView(activity);scroll.addView(layout);final boolean[] approved={false};AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("确认本次文字发送").setView(scroll).setNegativeButton("取消",null).setPositiveButton("同意本次发送（可能收费）",(d,w)->{if(!AiDisclosure.maySend(reviewed.isChecked(),requests.isCurrent(ticket)&&selection.isCurrent(ticket,snapshot)))return;approved[0]=true;recognize(ticket,snapshot,"food".equals(ticket.request.mode));}).create();dialog.setOnShowListener(d->{dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);reviewed.setOnCheckedChangeListener((b,checked)->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(AiDisclosure.maySend(checked,requests.isCurrent(ticket)&&selection.isCurrent(ticket,snapshot))));});dialog.setOnDismissListener(d->{dialogs.remove(dialog);if(!approved[0])finishSelection(ticket);});showDialog(dialog);}catch(Exception e){if(requests.release(ticket)){activeTicket=null;selection.invalidate(ticket);AiErrors.Info error=AiErrors.forCode("input");emit(ticket,"error",null,error.message,error.code);showFailure(error);}}}
 private void selected(Uri uri,boolean food){selected(activeTicket,uri,food);}
 private void selected(AiRequestSession.Ticket ticket,Uri uri,boolean food){if(!requests.isCurrent(ticket)||food!="food".equals(ticket.request.mode))return;try{
  ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=activity.getContentResolver().openInputStream(uri)){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>10*1024*1024)throw new IOException("请选择 10 MB 以内的图片");out.write(b,0,n);}}byte[] original=out.toByteArray();BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(original,0,original.length,o);if(o.outWidth<1||o.outHeight<1||o.outWidth>8192||o.outHeight>8192)throw new IOException("请选择边长不超过 8192 像素的清晰截图");String mime=o.outMimeType;if(!"image/png".equals(mime)&&!"image/jpeg".equals(mime)&&!"image/webp".equals(mime))throw new IOException("支持 PNG、JPEG 或 WebP 图片");AiImagePolicy.plan(o.outWidth,o.outHeight,food,readOrientation(original),bitmapBudget());final byte[] bytes=sanitizePhoto(original,food);final String sentMime=food?"image/jpeg":"image/png";final AiConsentSnapshot snapshot=new AiConsentSnapshot(ticket,bytes,sentMime,approvedImage->AiPayloadBuilder.image(ticket.request,approvedImage,sentMime));selection.replace(ticket,snapshot);
  confirmImage(ticket,snapshot,food);
 }catch(Exception|OutOfMemoryError e){if(requests.release(ticket)){activeTicket=null;sourceLauncher=null;selection.invalidate(ticket);AiErrors.Info error=AiErrors.forCode("input");emit(ticket,"error",null,error.message,error.code);showFailure(error);}}}
 private void confirmImage(AiRequestSession.Ticket ticket,AiConsentSnapshot snapshot,boolean food)throws IOException{if(!requests.isCurrent(ticket))return;selection.replace(ticket,snapshot);emit(ticket,"phase","consent",null);
  byte[] previewBytes=snapshot.copyImageBytes();BitmapFactory.Options sentBounds=new BitmapFactory.Options();sentBounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(previewBytes,0,previewBytes.length,sentBounds);
  LinearLayout layout=new LinearLayout(activity);layout.setOrientation(1);layout.setPadding(32,12,32,8);TextView text=new TextView(activity);text.setText((ticket.request.retryOf!=null?"重新发送同一图片可能再次收费，请重新确认。\n":"")+AiDisclosure.image(ticket.request,sentBounds.outWidth,sentBounds.outHeight,previewBytes.length));text.setTextIsSelectable(true);layout.addView(text);
  ImageView image=new ImageView(activity);BitmapFactory.Options preview=new BitmapFactory.Options();preview.inSampleSize=AiImagePolicy.previewSample(sentBounds.outWidth,sentBounds.outHeight);preview.inPreferredConfig=Bitmap.Config.ARGB_8888;Bitmap bm=BitmapFactory.decodeByteArray(previewBytes,0,previewBytes.length,preview);if(bm==null)throw new IOException("无法显示发送预览，请重新选择");image.setImageBitmap(bm);image.setContentDescription("本次实际发送图片的预览，"+sentBounds.outWidth+" × "+sentBounds.outHeight+" 像素");image.setAdjustViewBounds(true);image.setMaxHeight(650);layout.addView(image);
  Button reveal=new Button(activity);reveal.setText("查看本次固定识别说明");layout.addView(reveal);TextView instructions=new TextView(activity);instructions.setText(AiPayloadBuilder.instruction(ticket.request));instructions.setTextIsSelectable(true);instructions.setVisibility(View.GONE);layout.addView(instructions);reveal.setOnClickListener(v->{boolean hidden=instructions.getVisibility()!=View.VISIBLE;instructions.setVisibility(hidden?View.VISIBLE:View.GONE);reveal.setText(hidden?"收起固定识别说明":"查看本次固定识别说明");});CheckBox redaction=new CheckBox(activity);redaction.setText("我已检查发送预览，移除完整卡号、账号、密码、验证码和 API 密钥，仅保留本次识别所需内容");redaction.setChecked(false);layout.addView(redaction);ScrollView scroll=new ScrollView(activity);scroll.addView(layout);
  final boolean[] approved={false};final Runnable reselect=sourceLauncher;AlertDialog d=new AlertDialog.Builder(activity).setTitle(food?"确认发送食物照片？":"确认发送这张截图？").setView(scroll).setNegativeButton("取消",null).setNeutralButton("换一张（不发送）",(x,w)->{if(!requests.isCurrent(ticket)||!selection.isCurrent(ticket,snapshot))return;selection.invalidate(ticket);approved[0]=true;if(reselect!=null)reselect.run();else finishSelection(ticket);}).setPositiveButton("同意本次发送（可能收费）",(x,w)->{if(!AiDisclosure.maySend(redaction.isChecked(),requests.isCurrent(ticket)&&selection.isCurrent(ticket,snapshot)))return;approved[0]=true;recognize(ticket,snapshot,food);}).create();d.setOnShowListener(x->{d.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);d.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);if(ticket.request.retryOf!=null)d.getButton(AlertDialog.BUTTON_NEUTRAL).setVisibility(View.GONE);redaction.setOnCheckedChangeListener((button,checked)->d.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(AiDisclosure.maySend(checked,requests.isCurrent(ticket)&&selection.isCurrent(ticket,snapshot))));});d.setOnDismissListener(x->{dialogs.remove(d);bm.recycle();if(!approved[0])finishSelection(ticket);});showDialog(d);
 }
 private void recognize(AiRequestSession.Ticket ticket,AiConsentSnapshot snapshot,boolean food){if(!requests.isCurrent(ticket.sessionId,ticket.id,ticket.generation,ticket.request.mode,ticket.request.source,ticket.request.revision)||!selection.consume(ticket,snapshot))return;String key=loadKey();if(key.isEmpty()){finishSelection(ticket);message("请先配置密钥");return;}final DeepSeekTransport requestTransport=new DeepSeekTransport();transport=requestTransport;emit(ticket,"phase","sending",null);new Thread(()->{String answer=null;AiErrors.Info failure=null;try{ answer=AiResponseParser.parse(requestTransport.send(key,snapshot.payload()),ticket.request.mode);
 }catch(Exception e){failure=AiErrors.from(e);}final String ok=answer;final AiErrors.Info error=failure;activity.runOnUiThread(()->{if(!requests.release(ticket))return;activeTicket=null;sourceLauncher=null;selection.invalidate(ticket);if(transport==requestTransport)transport=null;if(!activity.isFinishing()&&!activity.isDestroyed()){if(ok!=null){emit(ticket,"result",ok,null);}else {if(!"cancelled".equals(error.code))retryStore.offer(ticket,snapshot);emit(ticket,"error",null,error.message,error.code);showFailure(error);}}});},"statement-recognition").start();}
 private void showFailure(AiErrors.Info error){if(!requests.isAlive()||activity.isFinishing()||activity.isDestroyed())return;AlertDialog.Builder builder=new AlertDialog.Builder(activity).setTitle("识别未完成").setMessage(error.message+"\n取消或失败后服务仍可能已计费。应用不会自动重试；再次发送可能再次收费。").setNegativeButton("继续本地记录",null);if("configure".equals(error.action))builder.setPositiveButton("配置密钥",(d,w)->configure(null));else builder.setPositiveButton("知道了",null);AlertDialog dialog=builder.create();dialog.setOnDismissListener(d->dialogs.remove(dialog));showDialog(dialog);}
 private long bitmapBudget(){return Math.min(AiImagePolicy.MAX_BITMAP_BUDGET,Math.max(8L,Runtime.getRuntime().maxMemory()/4));}
 private int readOrientation(byte[] original){try{android.media.ExifInterface exif=new android.media.ExifInterface(new ByteArrayInputStream(original));return exif.getAttributeInt(android.media.ExifInterface.TAG_ORIENTATION,1);}catch(IOException e){return 1;}}
 private Bitmap orient(Bitmap bitmap,int orientation){if(orientation==1)return bitmap;Matrix matrix=new Matrix();switch(orientation){case 2:matrix.setScale(-1,1);break;case 3:matrix.setRotate(180);break;case 4:matrix.setScale(1,-1);break;case 5:matrix.setRotate(90);matrix.postScale(-1,1);break;case 6:matrix.setRotate(90);break;case 7:matrix.setRotate(-90);matrix.postScale(-1,1);break;case 8:matrix.setRotate(270);break;default:throw new IllegalArgumentException("图片方向无效");}Bitmap rotated=Bitmap.createBitmap(bitmap,0,0,bitmap.getWidth(),bitmap.getHeight(),matrix,true);if(rotated!=bitmap)bitmap.recycle();return rotated;}
 private byte[] sanitizePhoto(byte[] original,boolean food)throws IOException{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(original,0,original.length,bounds);int orientation=readOrientation(original);AiImagePolicy.Plan plan=AiImagePolicy.plan(bounds.outWidth,bounds.outHeight,food,orientation,bitmapBudget());BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=plan.sampleSize;options.inPreferredConfig=Bitmap.Config.ARGB_8888;Bitmap bitmap=BitmapFactory.decodeByteArray(original,0,original.length,options);if(bitmap==null)throw new IOException("照片无法解码");try{bitmap=orient(bitmap,orientation);AiBoundedBytes out=new AiBoundedBytes(AiBoundedBytes.MAX_BYTES);if(!bitmap.compress(food?Bitmap.CompressFormat.JPEG:Bitmap.CompressFormat.PNG,food?90:100,out))throw new IOException("图片处理失败或超过大小限制");return out.toByteArray();}finally{bitmap.recycle();}}
 void resetPage(){deliveries.invalidate();deliveryOwners.clear();sources.reset();retryStore.clear();pageGeneration++;requests.reset();activeTicket=null;sourceLauncher=null;selection.reset();DeepSeekTransport old=transport;transport=null;if(old!=null)old.cancel();for(Dialog dialog:new java.util.ArrayList<Dialog>(dialogs))dialog.dismiss();dialogs.clear();}
 void destroy(){deliveries.close();requests.close();resetPage();sessionKey="";}
 private void showDialog(Dialog dialog){if(!requests.isAlive()||activity.isFinishing()||activity.isDestroyed())return;dialogs.add(dialog);dialog.show();}

 private void message(String s){if(!requests.isAlive()||activity.isFinishing()||activity.isDestroyed())return;AlertDialog dialog=new AlertDialog.Builder(activity).setMessage(s).setPositiveButton("知道了",null).create();dialog.setOnDismissListener(d->dialogs.remove(dialog));showDialog(dialog);}
}
